(()=>{'use strict';const {q,shuffle,pick,show,hide,passScreen,makePlayers,toast,beep,haptic}=SC23;const root=q('#gameRoot');
const QUESTIONS=[
['¿Qué animal hace excrementos con forma casi cúbica?','El wombat'],['¿Qué país tiene al unicornio como animal nacional?','Escocia'],['¿Cuántos corazones tiene un pulpo?','Tres'],['¿Cuál es el hueso más pequeño del cuerpo humano?','El estribo'],['¿Qué fruta es botánicamente una baya aunque no lo parezca?','El plátano'],['¿Por qué los flamencos son rosas?','Por los carotenoides de su dieta'],['¿Qué mamífero pone huevos?','El ornitorrinco'],['¿Qué planeta gira prácticamente tumbado sobre su eje?','Urano'],['¿Cuál es el único continente sin reptiles terrestres nativos?','La Antártida'],['¿Qué animal puede dormir de pie y también tumbado?','El caballo'],['¿Qué metal es líquido a temperatura ambiente?','El mercurio'],['¿Qué ave puede volar hacia atrás de forma sostenida?','El colibrí'],['¿Qué órgano humano puede regenerar gran parte de su masa?','El hígado'],['¿Qué país tiene más pirámides que Egipto?','Sudán'],['¿Qué animal tiene tres párpados?','El camello'],['¿Qué planeta tiene el día más largo del sistema solar?','Venus'],['¿Qué parte del cuerpo humano no tiene vasos sanguíneos?','La córnea'],['¿Qué mamífero terrestre tiene la presión sanguínea más alta?','La jirafa'],['¿Qué alimento puede durar siglos sin estropearse si se conserva bien?','La miel'],['¿Qué animal tiene huellas dactilares muy parecidas a las humanas?','El koala'],['¿Qué país inventó el papel?','China'],['¿Qué animal tiene la lengua más larga en proporción a su cuerpo entre los mamíferos conocidos?','El murciélago nectarívoro'],['¿Qué planeta es el más caliente aunque no sea el más cercano al Sol?','Venus'],['¿Qué parte del ojo da su color característico?','El iris'],['¿Qué gas constituye la mayor parte de la atmósfera terrestre?','El nitrógeno'],['¿Qué animal marino tiene sangre azul por usar hemocianina?','El cangrejo herradura'],['¿Qué ave tiene los ojos más grandes que su cerebro?','El avestruz'],['¿Cuál es el mamífero más grande del mundo?','La ballena azul'],['¿Qué animal puede saborear con las patas?','La mariposa'],['¿Qué material natural es más duro?','El diamante']
].map(([question,answer])=>({question,answer}));
let st={players:[],round:0,fisher:0,q:null,trueHolder:null,responders:[],responses:[],idx:0,roundPts:0,resolved:false};
function renderSetup(){root.innerHTML=`<section class="v23-grid"><div class="v23-panel"><h2>Preparar partida</h2><p>Solo hace falta un móvil. No se guardan nombres ni perfiles.</p><div class="v23-field"><label>Número de personas</label><select id="count">${[4,5,6,7,8,9,10].map(n=>`<option>${n}</option>`).join('')}</select></div><div class="v23-actions"><button id="start" class="v23-btn primary big wide">Empezar a pescar</button></div></div><div class="v23-panel soft"><h3>Qué hace el móvil</h3><p>Reparte en secreto la respuesta verdadera, recoge los faroles y se los muestra al pescador totalmente mezclados.</p></div></section>`;q('#start').onclick=start}
function scores(){return `<div class="v23-scoreboard">${st.players.map((p,i)=>`<div class="v23-score ${i===st.fisher?'current':''}"><strong>${p.name}</strong><span>${p.score} pt${p.score===1?'':'s'}</span></div>`).join('')}</div>`}
function start(){st.players=makePlayers(+q('#count').value);st.round=0;nextRound()}
function nextRound(){st.round++;st.fisher=(st.round-1)%st.players.length;st.q=pick(QUESTIONS);st.responders=st.players.map((_,i)=>i).filter(i=>i!==st.fisher);st.trueHolder=pick(st.responders);st.responses=[];st.idx=0;st.roundPts=0;st.resolved=false;root.innerHTML=`<section class="v23-panel"><div class="v23-status"><span>Ronda <strong>${st.round}</strong></span><span>Pescador: <strong>${st.players[st.fisher].name}</strong></span></div><div style="margin-top:14px">${scores()}</div><h2 class="v23-question">${st.q.question}</h2><p class="v23-subtitle">El pescador debe apartar la vista mientras el resto prepara las respuestas.</p><div class="v23-actions"><button id="deal" class="v23-btn primary big wide">Repartir respuestas secretas</button></div></section>`;q('#deal').onclick=collectNext}
function collectNext(){if(st.idx>=st.responders.length){showFishing();return}const pi=st.responders[st.idx];passScreen(`Pasa el móvil a ${st.players[pi].name}`,'El pescador no puede mirar.',()=>secretTurn(pi),'🐟')}
function secretTurn(pi){const isTrue=pi===st.trueHolder;root.innerHTML=`<section class="v23-panel v23-center"><div class="v23-status"><span>${st.players[pi].name}</span><span>Respuesta ${st.idx+1}/${st.responders.length}</span></div><div class="v23-icon" style="margin:22px auto">${isTrue?'🔵':'🔴'}</div><h2>${isTrue?'Tú tienes la respuesta verdadera':'Inventa una respuesta falsa'}</h2><p>${isTrue?'Memorízala. El móvil la añadirá automáticamente a la lista.':'Escribe algo creíble, raro o descaradamente sospechoso. No copies la respuesta real.'}</p>${isTrue?`<div class="v23-panel soft"><div class="v23-question" style="font-size:clamp(26px,6vw,44px)">${st.q.answer}</div></div>`:`<div class="v23-field"><label>Tu respuesta falsa</label><textarea id="fake" maxlength="110" placeholder="Escribe aquí tu farol..."></textarea></div>`}<div class="v23-actions"><button id="done" class="v23-btn primary big wide">Guardar y pasar móvil</button></div></section>`;q('#done').onclick=()=>{let text=st.q.answer;if(!isTrue){text=q('#fake').value.trim();if(text.length<2){toast('Escribe una respuesta antes de continuar');return}}st.responses.push({text,true:isTrue,author:pi,revealed:false});st.idx++;passScreen(st.idx<st.responders.length?`Pasa el móvil al siguiente jugador`:`Devuelve el móvil al pescador`,st.idx<st.responders.length?'Que nadie vea la pantalla anterior.':'Las respuestas ya están mezclándose.',()=>collectNext(),st.idx<st.responders.length?'📱':'🎣')}}
function showFishing(){st.responses=shuffle(st.responses);root.innerHTML=`<section class="v23-panel"><div class="v23-status"><span>Pescador: <strong>${st.players[st.fisher].name}</strong></span><span>Botín de ronda: <strong id="loot">0</strong></span></div><h2 class="v23-question">${st.q.question}</h2><p class="v23-subtitle">Pulsa «Chao Pescao» sobre una respuesta que creas inventada. Si pescas la verdadera, pierdes el botín de la ronda.</p><div id="answers" class="v23-answer-list"></div><div class="v23-actions"><button id="bank" class="v23-btn good big wide" disabled>Plantarse y guardar puntos</button></div></section>`;renderAnswers();q('#bank').onclick=bank}
function renderAnswers(){const box=q('#answers');box.innerHTML=st.responses.map((r,i)=>`<div class="v23-answer ${r.revealed?'revealed '+(r.true?'true':'false'):''}"><span class="badge">${i+1}</span><p>${escapeHtml(r.text)}</p>${r.revealed?`<strong>${r.true?'VERDAD':'FALSA'}</strong>`:`<button class="v23-btn" data-fish="${i}">Chao Pescao</button>`}</div>`).join('');box.querySelectorAll('[data-fish]').forEach(b=>b.onclick=()=>fish(+b.dataset.fish));q('#loot').textContent=st.roundPts;q('#bank').disabled=st.roundPts===0||st.resolved}
function fish(i){if(st.resolved)return;const r=st.responses[i];if(r.revealed)return;r.revealed=true;if(r.true){st.resolved=true;beep(150,.35,'sawtooth',.07);haptic([100,60,180]);const survivors=st.responses.filter(x=>!x.revealed&&!x.true);survivors.forEach(x=>st.players[x.author].score++);st.players[st.trueHolder].score++;st.roundPts=0;renderAnswers();setTimeout(()=>roundResult(false),550)}else{st.roundPts++;beep(780,.08);haptic(30);renderAnswers();if(st.responses.filter(x=>!x.true&&!x.revealed).length===0){bank()}}}
function bank(){if(st.resolved)return;st.resolved=true;st.players[st.fisher].score+=st.roundPts;roundResult(true)}
function roundResult(success){root.innerHTML=`<section class="v23-panel v23-center"><div class="v23-icon" style="margin:0 auto 16px">${success?'🏆':'💥'}</div><h2>${success?'Buena pesca':'¡Has pescado la verdad!'}</h2><p>${success?`${st.players[st.fisher].name} guarda ${st.roundPts} punto${st.roundPts===1?'':'s'} de esta ronda.`:`${st.players[st.fisher].name} pierde el botín. La respuesta verdadera era: <strong>${st.q.answer}</strong>.`}</p>${scores()}<div class="v23-actions"><button id="next" class="v23-btn primary big wide">Siguiente ronda</button></div></section>`;q('#next').onclick=nextRound}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
renderSetup();})();
