(()=>{
'use strict';
const DECK={
Curiosidades:[
{q:'¿Cómo se llama el olor característico que aparece cuando la lluvia cae sobre suelo seco?',a:'Petricor'},{q:'¿Cuántos puntos suman en total todas las caras de dos dados normales de seis caras?',a:'42'},{q:'Botánicamente, ¿qué fruta es una baya aunque normalmente no la llamemos así?',a:'El plátano'},{q:'¿Qué parte transparente del ojo humano no tiene vasos sanguíneos?',a:'La córnea'},{q:'¿Cuántos minutos tiene exactamente una semana?',a:'10.080 minutos'},{q:'¿Cómo se llama una palabra o frase que puede leerse igual de izquierda a derecha que al revés?',a:'Palíndromo'},{q:'¿Qué instrumento musical estándar tiene normalmente 88 teclas?',a:'El piano'},{q:'¿Qué forma geométrica tiene normalmente una señal de STOP?',a:'Octágono'},{q:'¿Qué objeto apareció antes históricamente: el mechero o la cerilla de fricción?',a:'El mechero'},{q:'¿Qué alimento destaca por poder conservarse durante muchísimo tiempo gracias a su baja humedad y acidez?',a:'La miel'},{q:'¿Qué día de la semana en español debe su nombre a la Luna?',a:'Lunes'},{q:'¿Qué “dirección” invierte realmente un espejo plano?',a:'Delante y detrás, no izquierda y derecha'}],
Animales:[
{q:'¿Qué animal tiene tres corazones?',a:'El pulpo'},{q:'¿Qué mamífero produce excrementos con forma casi cúbica?',a:'El wombat'},{q:'¿Qué animal puede saborear con receptores situados en sus patas?',a:'La mariposa'},{q:'¿En qué animal es el macho quien lleva los embriones hasta el nacimiento?',a:'El caballito de mar'},{q:'¿Qué ave obtiene gran parte de su color rosado de pigmentos presentes en su dieta?',a:'El flamenco'},{q:'¿Qué marsupial tiene huellas dactilares sorprendentemente parecidas a las humanas?',a:'El koala'},{q:'¿Qué gran pez tiene un esqueleto formado principalmente por cartílago y no por huesos?',a:'El tiburón'},{q:'¿Qué ave terrestre tiene unos ojos más grandes que su cerebro?',a:'El avestruz'},{q:'¿Qué animal marino puede dormir manteniendo activa aproximadamente una mitad del cerebro?',a:'El delfín'},{q:'¿Qué ave es conocida por reconocer y recordar rostros humanos concretos?',a:'El cuervo'},{q:'¿Qué mamífero es el pariente vivo terrestre más cercano de las ballenas?',a:'El hipopótamo'},{q:'¿Qué animal puede regenerar brazos y, en algunas especies, partes de órganos internos?',a:'La estrella de mar'}],
Ciencia:[
{q:'¿Cuál es el planeta más caliente del Sistema Solar?',a:'Venus'},{q:'¿Qué metal es líquido a temperatura ambiente?',a:'Mercurio'},{q:'¿Cuál es el gas más abundante de la atmósfera terrestre?',a:'Nitrógeno'},{q:'¿Puede propagarse el sonido por el vacío?',a:'No'},{q:'¿Qué planeta gira con su eje tan inclinado que parece hacerlo tumbado?',a:'Urano'},{q:'¿Qué le ocurre al agua al congelarse: ocupa más o menos volumen?',a:'Ocupa más volumen'},{q:'¿Cuál es el órgano más grande del cuerpo humano?',a:'La piel'},{q:'¿Cuál es el planeta más grande del Sistema Solar?',a:'Júpiter'},{q:'Aproximadamente, ¿a qué velocidad viaja la luz en el vacío?',a:'300.000 km/s'},{q:'¿Qué elemento químico tiene el símbolo W?',a:'Wolframio o tungsteno'},{q:'¿Qué valor de pH se considera neutro a temperatura ambiente?',a:'7'},{q:'¿De qué elemento están formados tanto el diamante como el grafito?',a:'Carbono'}],
Mundo:[
{q:'¿Cuál es el país soberano más pequeño del mundo por superficie?',a:'Ciudad del Vaticano'},{q:'¿Cuál es la capital de Australia?',a:'Canberra'},{q:'¿Cuál es el desierto más grande del planeta si contamos los desiertos polares?',a:'La Antártida'},{q:'¿Qué país tiene la costa más larga del mundo?',a:'Canadá'},{q:'¿Qué gran ciudad está repartida entre Europa y Asia por el estrecho del Bósforo?',a:'Estambul'},{q:'¿Qué continente está atravesado por el ecuador y por el meridiano de Greenwich?',a:'África'},{q:'¿Cuál es el lago más grande del mundo por superficie?',a:'El mar Caspio'},{q:'¿Qué río atraviesa Budapest?',a:'El Danubio'},{q:'¿Cuál es la capital constitucional de Bolivia?',a:'Sucre'},{q:'¿Cuál es el salto de agua más alto del mundo?',a:'El Salto Ángel'},{q:'¿En qué país se encuentra la ciudad de Petra?',a:'Jordania'},{q:'¿Qué país europeo tiene forma de bota en los mapas?',a:'Italia'}],
Historia:[
{q:'¿Qué guerra de 1896 es famosa por haber durado menos de una hora?',a:'La guerra anglo-zanzibariana'},{q:'¿Quién fue la primera persona en pisar la Luna?',a:'Neil Armstrong'},{q:'¿En qué año cayó el Muro de Berlín?',a:'1989'},{q:'¿Qué volcán sepultó Pompeya en el año 79?',a:'El Vesubio'},{q:'¿En qué país nacieron los Juegos Olímpicos de la Antigüedad?',a:'Grecia'},{q:'¿Qué piedra fue clave para descifrar los jeroglíficos egipcios?',a:'La piedra de Rosetta'},{q:'¿Qué civilización andina utilizó los quipus para registrar información?',a:'La civilización inca'},{q:'¿En qué ciudad se celebraron los primeros Juegos Olímpicos modernos en 1896?',a:'Atenas'},{q:'¿Quién completó al mando la primera vuelta al mundo tras la muerte de Magallanes?',a:'Juan Sebastián Elcano'},{q:'¿En qué año llegó la expedición de Colón a América?',a:'1492'},{q:'¿Cómo se llamó durante siglos la capital del Imperio bizantino?',a:'Constantinopla'},{q:'¿Qué tipo de escritura desarrollaron los sumerios en Mesopotamia?',a:'La escritura cuneiforme'}],
Cultura:[
{q:'¿Lleva monóculo el personaje clásico del Monopoly?',a:'No'},{q:'¿Aparece literalmente “Elemental, querido Watson” en los relatos originales de Conan Doyle?',a:'No'},{q:'¿Cuántas casillas tiene un tablero de ajedrez?',a:'64'},{q:'¿Quién pintó el Guernica?',a:'Pablo Picasso'},{q:'¿Quién pintó El grito?',a:'Edvard Munch'},{q:'¿Quién escribió Don Quijote de la Mancha?',a:'Miguel de Cervantes'},{q:'¿En qué museo se expone la Mona Lisa?',a:'El Louvre'},{q:'¿Cómo se llamó originalmente Pac-Man en Japón?',a:'Puck Man'},{q:'¿Cuál es el nombre oficial de la estatuilla de los Óscar?',a:'Academy Award of Merit'},{q:'¿Quién escribió la novela 1984?',a:'George Orwell'},{q:'¿Cuántas cuerdas tiene normalmente un violín?',a:'4'},{q:'¿Qué pieza de ajedrez puede saltar por encima de otras?',a:'El caballo'}],
Comida:[
{q:'¿El cacahuete es botánicamente un fruto seco o una legumbre?',a:'Una legumbre'},{q:'¿De qué tipo de planta procede la vainilla?',a:'De una orquídea'},{q:'¿A qué se refiere originalmente la palabra sushi: al pescado crudo o al arroz preparado?',a:'Al arroz avinagrado'},{q:'¿Cuál es el ingrediente principal del hummus tradicional?',a:'Garbanzos'},{q:'¿Cuál es el ingrediente principal del guacamole?',a:'Aguacate'},{q:'¿De qué legumbre se elabora principalmente el tofu?',a:'Soja'},{q:'¿Qué parte de la flor del azafrán se recolecta como especia?',a:'Los estigmas'},{q:'¿De qué planta se obtiene tradicionalmente el tequila?',a:'Agave azul'},{q:'¿Qué son en realidad los llamados “granos” de café?',a:'Semillas de un fruto'},{q:'¿El chocolate blanco contiene sólidos de cacao?',a:'No'},{q:'¿Qué sustancia da tradicionalmente el amargor característico al agua tónica?',a:'Quinina'},{q:'¿Qué parte de la planta se utiliza en el wasabi auténtico?',a:'El rizoma'}],
'Sala Cero':[
{q:'¿Cuántas cartas tiene la baraja española habitual utilizada en Tute?',a:'40'},{q:'¿Cuántos dados se lanzan en una partida estándar de Generala?',a:'5'},{q:'¿Qué dos cartas forman un blackjack natural?',a:'Un as y una carta de valor 10'},{q:'¿Qué suma hay que conseguir para hacer una escoba?',a:'15'},{q:'¿Cuántas cartas privadas recibe cada jugador en Texas Hold’em?',a:'2'},{q:'¿Cuánto valen las figuras en el juego de Siete y media?',a:'Medio punto'},{q:'¿Cuántos palos tiene una baraja española?',a:'4'},{q:'¿Cuántos puntos vale el as en el Tute?',a:'11 puntos'},{q:'¿Cuántos puntos vale el tres en el Tute?',a:'10 puntos'},{q:'¿Qué jugada de póker forman A, K, Q, J y 10 del mismo palo?',a:'Escalera real'},{q:'¿Cómo se llama en Blackjack la acción de dividir dos cartas iguales en dos manos?',a:'Separar o split'},{q:'En una Generala, ¿cuántos dados deben mostrar el mismo número?',a:'Los 5'}]
};
const $=id=>document.getElementById(id),U={};let cfg=null,game=null,secretIndex=0,toastTimer=0;const stages=['cpQuestionStage','cpHandoff','cpSecret','cpReturn','cpFishing','cpRoundResult','cpFinal'];
function boot(){['cpWelcome','cpConfigure','cpSetup','cpSetupClose','cpCount','cpLength','cpCategory','cpNames','cpStart','cpGame','cpRoundLabel','cpFisherLabel','cpScoreToggle','cpScoreDrawer','cpScoreList','cpQuestionStage','cpFisherName','cpQuestionCategory','cpQuestion','cpPassToFish','cpHandoff','cpHandoffName','cpRevealRole','cpSecret','cpSecretCard','cpRoleKicker','cpRoleTitle','cpRoleText','cpRealAnswer','cpHideRole','cpReturn','cpReturnName','cpBackToFisher','cpFishing','cpLiveFisher','cpRoundPoints','cpLiveQuestion','cpSuspects','cpBank','cpBankPoints','cpRoundResult','cpResultIcon','cpResultTitle','cpResultText','cpAnswerReveal','cpDeltas','cpNextRound','cpFinal','cpWinnerTitle','cpWinnerText','cpFinalBoard','cpReplay','cpNewGame','cpToast'].forEach(k=>U[k]=$(k));U.cpCount.innerHTML=Array.from({length:7},(_,i)=>`<option value="${i+4}" ${i===2?'selected':''}>${i+4} jugadores</option>`).join('');U.cpCategory.innerHTML=`<option value="Mezcla">Mezcla de todo</option>${Object.keys(DECK).map(k=>`<option value="${esc(k)}">${esc(k)}</option>`).join('')}`;renderNames();U.cpCount.onchange=renderNames;U.cpConfigure.onclick=showSetup;U.cpSetupClose.onclick=showWelcome;U.cpStart.onclick=startGame;U.cpScoreToggle.onclick=()=>U.cpScoreDrawer.classList.toggle('hidden');U.cpPassToFish.onclick=startSecrets;U.cpRevealRole.onclick=revealRole;U.cpHideRole.onclick=hideRole;U.cpBackToFisher.onclick=startFishing;U.cpBank.onclick=bankRound;U.cpNextRound.onclick=nextRound;U.cpReplay.onclick=replay;U.cpNewGame.onclick=showSetup}
function renderNames(){const n=+U.cpCount.value||6,old=[...U.cpNames.querySelectorAll('input')].map(x=>x.value);U.cpNames.innerHTML=Array.from({length:n},(_,i)=>`<input maxlength="18" aria-label="Nombre del jugador ${i+1}" value="${esc(old[i]||`Jugador ${i+1}`)}">`).join('')}
function showWelcome(){U.cpSetup.classList.add('hidden');U.cpGame.classList.add('hidden');U.cpWelcome.classList.remove('hidden');topNow()}
function showSetup(){U.cpWelcome.classList.add('hidden');U.cpGame.classList.add('hidden');U.cpSetup.classList.remove('hidden');renderNames();topNow()}
function startGame(){const names=[...U.cpNames.querySelectorAll('input')].map((x,i)=>clean(x.value,`Jugador ${i+1}`));if(new Set(names.map(n=>n.toLowerCase())).size!==names.length){toast('Pon nombres distintos para que la pesca no se líe.');return}cfg={names,loops:+U.cpLength.value||1,category:U.cpCategory.value};game={scores:names.map(()=>0),round:0,total:names.length*cfg.loops,startFisher:Math.floor(Math.random()*names.length),used:[],current:null};U.cpSetup.classList.add('hidden');U.cpWelcome.classList.add('hidden');U.cpGame.classList.remove('hidden');U.cpScoreDrawer.classList.add('hidden');beginRound()}
function replay(){game={scores:cfg.names.map(()=>0),round:0,total:cfg.names.length*cfg.loops,startFisher:Math.floor(Math.random()*cfg.names.length),used:[],current:null};beginRound()}
function beginRound(){if(game.round>=game.total){showFinal();return}const fisher=(game.startFisher+game.round)%cfg.names.length,fish=cfg.names.map((_,i)=>i).filter(i=>i!==fisher),blue=fish[Math.floor(Math.random()*fish.length)],card=pickCard();game.current={fisher,fish,blue,card,caught:new Set(),risk:0,deltas:cfg.names.map(()=>0),ended:false};secretIndex=0;U.cpRoundLabel.textContent=`RONDA ${game.round+1} / ${game.total}`;U.cpFisherLabel.textContent=`Pesca ${cfg.names[fisher]}`;U.cpFisherName.textContent=cfg.names[fisher];U.cpQuestionCategory.textContent=card.cat.toUpperCase();U.cpQuestion.textContent=card.q;renderScores();showStage('cpQuestionStage');topNow()}
function pickCard(){let pool=[];if(cfg.category==='Mezcla')Object.entries(DECK).forEach(([cat,arr])=>arr.forEach((x,i)=>pool.push({...x,cat,key:`${cat}:${i}`})));else(DECK[cfg.category]||DECK.Curiosidades).forEach((x,i)=>pool.push({...x,cat:cfg.category,key:`${cfg.category}:${i}`}));let available=pool.filter(x=>!game.used.includes(x.key));if(!available.length){game.used=[];available=pool}const card=available[Math.floor(Math.random()*available.length)];game.used.push(card.key);return card}
function startSecrets(){secretIndex=0;showHandoff()}
function showHandoff(){const idx=game.current.fish[secretIndex];U.cpHandoffName.textContent=cfg.names[idx];showStage('cpHandoff');topNow()}
function revealRole(){const idx=game.current.fish[secretIndex],blue=idx===game.current.blue;U.cpSecretCard.classList.toggle('blue',blue);U.cpRoleKicker.textContent=blue?'ERES PEZ AZUL':'ERES PEZ ROJO';U.cpRoleTitle.textContent=blue?'DI LA VERDAD':'MIENTE';U.cpRoleText.textContent=blue?'Tu trabajo es decir la respuesta real y conseguir que al pescador le parezca inventada.':'Inventa una respuesta falsa, breve y creíble. Intenta que el pescador piense que tú eres el pez azul.';U.cpRealAnswer.textContent=game.current.card.a;U.cpHideRole.textContent=secretIndex===game.current.fish.length-1?'Ocultar y devolver al pescador →':'Ocultar y pasar al siguiente →';showStage('cpSecret');navigator.vibrate?.(blue?[45,35,45]:20);topNow()}
function hideRole(){U.cpRealAnswer.textContent='—';secretIndex++;if(secretIndex>=game.current.fish.length){U.cpReturnName.textContent=cfg.names[game.current.fisher];showStage('cpReturn');topNow()}else showHandoff()}
function startFishing(){const c=game.current;U.cpLiveFisher.textContent=`${cfg.names[c.fisher]} pesca`;U.cpLiveQuestion.textContent=c.card.q;drawFishing();showStage('cpFishing');topNow()}
function drawFishing(){const c=game.current;U.cpRoundPoints.textContent=c.risk;U.cpBankPoints.textContent=c.risk;U.cpBank.disabled=c.ended;U.cpSuspects.innerHTML=c.fish.map(i=>{const caught=c.caught.has(i);return `<button class="cp-suspect ${caught?'caught':''}" data-fish="${i}" ${caught||c.ended?'disabled':''}><span><strong>${esc(cfg.names[i])}</strong><small>${caught?'PEZ ROJO ATRAPADO':'HA DADO SU RESPUESTA'}</small></span><b>${caught?'+1':'CHAO PESCAO'}</b></button>`}).join('');U.cpSuspects.querySelectorAll('[data-fish]').forEach(b=>b.onclick=()=>catchFish(+b.dataset.fish))}
function catchFish(i){const c=game.current;if(c.ended||c.caught.has(i))return;if(i===c.blue){c.ended=true;c.risk=0;finishRound('bust');navigator.vibrate?.([90,55,130]);return}c.caught.add(i);c.risk++;navigator.vibrate?.(25);toast(`Pez rojo. +1 provisional para ${cfg.names[c.fisher]}`);const reds=c.fish.filter(x=>x!==c.blue);if(reds.every(x=>c.caught.has(x))){c.ended=true;finishRound('perfect');return}drawFishing()}
function bankRound(){if(game.current.ended)return;game.current.ended=true;finishRound('bank')}
function finishRound(reason){const c=game.current,d=cfg.names.map(()=>0),uncaughtRed=c.fish.filter(i=>i!==c.blue&&!c.caught.has(i));let title='',text='',icon='✓',bust=false;if(reason==='bust'){uncaughtRed.forEach(i=>d[i]++);d[c.blue]++;title='¡Has pescado al azul!';text=`${cfg.names[c.fisher]} pierde los ${c.caught.size} punto${c.caught.size===1?'':'s'} provisionales. El pez azul y cada rojo que sobrevivió suman 1.`;icon='×';bust=true}else{d[c.fisher]+=c.risk;uncaughtRed.forEach(i=>d[i]++);if(reason==='perfect'){title='Pesca perfecta';text=`${cfg.names[c.fisher]} ha encontrado todos los peces rojos y guarda ${c.risk} punto${c.risk===1?'':'s'}.`}else{title=c.risk?'Te plantas a tiempo':'Caña recogida';text=`${cfg.names[c.fisher]} guarda ${c.risk} punto${c.risk===1?'':'s'}. Cada pez rojo que quedó sin descubrir suma 1.`}}c.deltas=d;d.forEach((v,i)=>game.scores[i]+=v);U.cpResultIcon.textContent=icon;U.cpResultIcon.classList.toggle('bust',bust);U.cpResultTitle.textContent=title;U.cpResultText.textContent=text;U.cpAnswerReveal.textContent=c.card.a;U.cpDeltas.innerHTML=cfg.names.map((n,i)=>`<article><span>${esc(n)}${i===c.blue?' · pez azul':''}</span><b class="${d[i]?'plus':'zero'}">${d[i]?`+${d[i]}`:'—'}</b></article>`).join('');U.cpNextRound.textContent=game.round+1>=game.total?'Ver resultado final →':'Siguiente ronda →';renderScores();showStage('cpRoundResult');topNow()}
function nextRound(){game.round++;beginRound()}
function showFinal(){renderScores();const ranking=cfg.names.map((n,i)=>({n,i,s:game.scores[i]})).sort((a,b)=>b.s-a.s||a.i-b.i),max=ranking[0]?.s||0,winners=ranking.filter(x=>x.s===max);U.cpWinnerTitle.textContent=winners.length>1?'Empate en lo más alto':'Tenemos campeón';U.cpWinnerText.textContent=winners.length>1?`${winners.map(x=>x.n).join(' y ')} terminan con ${max} puntos.`:`${winners[0].n} gana con ${max} puntos.`;U.cpFinalBoard.innerHTML=ranking.map((x,pos)=>`<article><span>${pos+1}. ${esc(x.n)}</span><b>${x.s} pt</b></article>`).join('');U.cpRoundLabel.textContent='PARTIDA TERMINADA';U.cpFisherLabel.textContent='Chao pescao';showStage('cpFinal');topNow()}
function renderScores(){if(!cfg||!game)return;U.cpScoreList.innerHTML=cfg.names.map((n,i)=>`<article><span>${esc(n)}</span><b>${game.scores[i]} pt</b></article>`).join('')}
function showStage(id){stages.forEach(s=>U[s].classList.toggle('hidden',s!==id))}function topNow(){window.scrollTo({top:0,behavior:'auto'})}function clean(v,f){return String(v||'').trim().replace(/\s+/g,' ').slice(0,18)||f}function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function toast(t){clearTimeout(toastTimer);U.cpToast.textContent=t;U.cpToast.classList.add('show');toastTimer=setTimeout(()=>U.cpToast.classList.remove('show'),1900)}
document.addEventListener('DOMContentLoaded',boot);
})();
