(() => {
  "use strict";
  const SUITS=["oros","copas","espadas","bastos"], RANKS=[1,2,3,4,5,6,7,10,11,12], SAVE="salaCeroChinchonV20";
  const LABEL={oros:"oros",copas:"copas",espadas:"espadas",bastos:"bastos"};
  const UI={}, state={active:false,mode:"solo",target:100,players:[],deck:[],discard:[],dealer:0,current:0,phase:"draw",selected:-1,round:0,revealed:true,log:[],winner:null,drawnId:null,drawSource:null,aiStyle:"calculating",aiDifficulty:"normal"};
  let toastTimer=null, dragIndex=null;
  document.addEventListener("DOMContentLoaded",init);
  function init(){cache();bind();const n=window.SalaCeroClub?.getData?.().profile?.name;if(n)UI.cName.value=n;renderNames();refreshContinue();const career=window.SalaCeroCareer?.getAiConfig?.("chinchon");if(career)startCareer(career);}
  function cache(){["cWelcome","cGame","cMusic","cSolo","cLocal","cContinue","cContinueTitle","cContinueMeta","cRules","cRulesModal","cRulesClose","cRulesOk","cSetup","cSetupForm","cSetupClose","cSetupTitle","cMode","cName","cTarget","cDifficultyField","cDifficulty","cLocalFields","cPlayerCount","cNames","cScorePanel","cScoreToggle","cScores","cTurnKicker","cTurnName","cPhase","cOpponentHand","cStock","cStockCount","cDiscard","cDiscardCard","cHandStatus","cHandAdvice","cMessage","cSort","cDiscardBtn","cCloseBtn","cHand","cMeldTitle","cMeldText","cLog","cExit","cHandoff","cHandoffName","cReveal","cRoundModal","cRoundTitle","cRoundResults","cNextRound","cToast"].forEach(id=>UI[id]=document.getElementById(id));}
  function bind(){UI.cSolo.onclick=()=>openSetup("solo");UI.cMusic.onclick=toggleMusic;UI.cLocal.onclick=()=>openSetup("local");UI.cContinue.onclick=continueGame;UI.cRules.onclick=()=>UI.cRulesModal.showModal();UI.cRulesClose.onclick=UI.cRulesOk.onclick=()=>UI.cRulesModal.close();UI.cSetupClose.onclick=()=>UI.cSetup.close();UI.cPlayerCount.onchange=renderNames;UI.cSetupForm.onsubmit=e=>{e.preventDefault();startFromSetup();};UI.cStock.onclick=()=>humanDraw("stock");UI.cDiscard.onclick=()=>humanDraw("discard");UI.cSort.onclick=sortHand;UI.cDiscardBtn.onclick=()=>humanDiscard(false);UI.cCloseBtn.onclick=()=>humanDiscard(true);UI.cExit.onclick=exitMenu;UI.cReveal.onclick=revealTurn;UI.cScoreToggle.onclick=()=>UI.cScorePanel.classList.toggle("expanded");UI.cNextRound.onclick=nextRound;document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.active&&state.mode==="local"&&state.revealed)showHandoff();});}
  function openSetup(mode){UI.cMode.value=mode;UI.cSetupTitle.textContent=mode==="solo"?"Partida contra Doña Virtud":"Partida local";UI.cLocalFields.classList.toggle("hidden",mode!=="local");UI.cDifficultyField.classList.toggle("hidden",mode!=="solo");renderNames();UI.cSetup.showModal();}
  function renderNames(){const count=Number(UI.cPlayerCount?.value||2);UI.cNames.innerHTML="";for(let i=0;i<count;i++){const l=document.createElement("label");l.className="sg-field";l.innerHTML=`<span>Jugador ${i+1}</span><input id="cLocalName${i}" maxlength="18" value="${i===0?escapeHtml(UI.cName?.value||"Eduardo"):`Jugador ${i+1}`}">`;UI.cNames.appendChild(l);}}
  function startFromSetup(){const mode=UI.cMode.value,count=mode==="solo"?2:Number(UI.cPlayerCount.value),club=window.SalaCeroClub?.getData?.().profile?.name||"Eduardo";const players=Array.from({length:count},(_,i)=>({name:mode==="solo"?(i===0?(UI.cName.value.trim()||club):"Doña Virtud"):(document.getElementById(`cLocalName${i}`)?.value.trim()||`Jugador ${i+1}`),isAI:mode==="solo"&&i===1,penalty:0,eliminated:false,hand:[]}));Object.assign(state,{active:true,mode,target:Number(UI.cTarget.value),players,deck:[],discard:[],dealer:0,current:0,phase:"draw",selected:-1,round:0,revealed:mode!=="local",log:[],winner:null,drawnId:null,drawSource:null,aiStyle:"calculating",aiDifficulty:UI.cDifficulty.value||"normal"});UI.cSetup.close();showGame();startRound();}
  function startCareer(cfg){const name=window.SalaCeroClub?.getData?.().profile?.name||"Jugador";Object.assign(state,{active:true,mode:"solo",target:70,players:[{name,isAI:false,penalty:0,eliminated:false,hand:[]},{name:cfg.name||"Doña Virtud",isAI:true,penalty:0,eliminated:false,hand:[]}],deck:[],discard:[],dealer:0,current:0,phase:"draw",selected:-1,round:0,revealed:true,log:[`Encuentro de carrera: ${cfg.matchLabel||cfg.competitionTitle}.`],winner:null,drawnId:null,drawSource:null,aiStyle:cfg.personality||"calculating",aiDifficulty:cfg.difficulty||"normal"});showGame();startRound();}
  function showGame(){UI.cWelcome.classList.add("hidden");UI.cGame.classList.remove("hidden");window.scrollTo(0,0);}
  function startRound(){state.round++;state.selected=-1;state.phase="draw";state.drawnId=null;state.drawSource=null;state.deck=shuffle(deck());state.discard=[];state.players.forEach(p=>p.hand=[]);const active=activeIndexes();for(let n=0;n<7;n++)active.forEach(i=>state.players[i].hand.push(state.deck.pop()));state.discard.push(state.deck.pop());state.current=nextActive(state.dealer);state.revealed=state.mode!=="local";log(`Ronda ${state.round}: reparte ${state.players[state.dealer].name}.`);render();save();if(state.mode==="local")showHandoff();else maybeAI();}
  function deck(){return SUITS.flatMap(s=>RANKS.map(r=>({id:`${s}-${r}`,suit:s,rank:r})));}
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function activeIndexes(){return state.players.map((p,i)=>p.eliminated?null:i).filter(i=>i!==null);}
  function nextActive(from){let i=from;do{i=(i+1)%state.players.length;}while(state.players[i].eliminated);return i;}
  function current(){return state.players[state.current];}
  function recycle(){if(state.deck.length)return true;if(state.discard.length<=1)return false;const top=state.discard.pop();state.deck=shuffle(state.discard.splice(0));state.discard=[top];log("Se vuelve a barajar el descarte.");return true;}
  function humanDraw(source){if(!state.active||!state.revealed||current().isAI||state.phase!=="draw")return;let card;if(source==="stock"){if(!recycle())return;card=state.deck.pop();}else{if(!state.discard.length)return;card=state.discard.pop();}current().hand.push(card);state.drawnId=card.id;state.drawSource=source;state.phase="discard";state.selected=-1;log(`${current().name} roba del ${source==="stock"?"mazo":"descarte"}.`);render();save();}
  function humanDiscard(close){if(state.phase!=="discard"||state.selected<0||current().isAI||!canDiscardIndex(state.selected))return;const idx=state.selected;if(close&&!canCloseAfter(idx))return;discardAt(idx,close);}
  function discardAt(idx,close){const p=current(),card=p.hand.splice(idx,1)[0];state.discard.push(card);playCardSound(close);state.selected=-1;state.drawnId=null;state.drawSource=null;log(`${p.name} descarta ${cardName(card)}${close?" y cierra":""}.`);if(close){toast("Cierre declarado");endRound(state.current);return;}state.phase="draw";state.current=nextActive(state.current);state.revealed=state.mode!=="local";render();save();if(state.mode==="local")showHandoff();else maybeAI();}
  async function maybeAI(){if(!state.active||!current().isAI)return;await wait(600);const p=current(),top=state.discard.at(-1);let source="stock";if(top){const withTop=[...p.hand,top],bestTop=bestDiscard(withTop,withTop.length-1);const baseline=analysis(p.hand).deadwood;if(bestTop.score<baseline)source="discard";}if((state.aiDifficulty==="easy"||state.aiStyle==="unpredictable")&&top&&Math.random()<.28)source=Math.random()<.5?"stock":"discard";let drawn;if(source==="stock"){recycle();drawn=state.deck.pop();}else drawn=state.discard.pop();p.hand.push(drawn);state.drawnId=drawn.id;state.drawSource=source;state.phase="discard";render();await wait(650);const forbidden=source==="discard"?p.hand.length-1:-1;let choice=bestDiscard(p.hand,forbidden);if((state.aiDifficulty==="easy"||state.aiStyle==="unpredictable")&&Math.random()<.24){const legal=p.hand.map((_,i)=>i).filter(i=>i!==forbidden);const index=legal[Math.floor(Math.random()*legal.length)];choice={index,score:analysis(p.hand.filter((_,i)=>i!==index)).deadwood};}const closeLimit=state.aiStyle==="aggressive"?2:5;const close=choice.score<=closeLimit;discardAt(choice.index,close);}
  function bestDiscard(hand,forbidden=-1){let best={index:0,score:Infinity};hand.forEach((_,i)=>{if(i===forbidden)return;const a=analysis(hand.filter((__,j)=>j!==i));let score=a.deadwood+(a.chinchon?-100:0);if(score<best.score||(score===best.score&&Math.random()<.25))best={index:i,score:a.deadwood,chinchon:a.chinchon};});return best;}
  function canDiscardIndex(idx){const card=current().hand[idx];return !(state.drawSource==="discard"&&card?.id===state.drawnId);}
  function canCloseAfter(idx){if(!canDiscardIndex(idx))return false;const a=analysis(current().hand.filter((_,i)=>i!==idx));return a.deadwood<=5;}
  function sortHand(){if(state.phase==="discard"||state.phase==="draw"){current().hand.sort((a,b)=>SUITS.indexOf(a.suit)-SUITS.indexOf(b.suit)||RANKS.indexOf(a.rank)-RANKS.indexOf(b.rank));state.selected=-1;render();save();}}
  function analysis(hand){const n=hand.length,total=hand.reduce((s,c)=>s+cardPoints(c),0),melds=[];const byRank={};hand.forEach((c,i)=>(byRank[c.rank]??=[]).push(i));Object.values(byRank).forEach(ids=>{if(ids.length>=3){combinations(ids,3).forEach(x=>melds.push({mask:mask(x),ids:x,type:"group"}));if(ids.length===4)melds.push({mask:mask(ids),ids:[...ids],type:"group"});}});SUITS.forEach(s=>{const ids=hand.map((c,i)=>c.suit===s?i:null).filter(i=>i!==null).sort((a,b)=>RANKS.indexOf(hand[a].rank)-RANKS.indexOf(hand[b].rank));for(let a=0;a<ids.length;a++)for(let b=a+2;b<ids.length;b++){const segment=ids.slice(a,b+1);let ok=true;for(let k=1;k<segment.length;k++)if(RANKS.indexOf(hand[segment[k]].rank)!==RANKS.indexOf(hand[segment[k-1]].rank)+1)ok=false;if(ok)melds.push({mask:mask(segment),ids:segment,type:"run"});}});let best={saved:0,chosen:[],used:0};function dfs(pos,used,saved,chosen){if(pos===melds.length){if(saved>best.saved)best={saved,chosen:[...chosen],used};return;}dfs(pos+1,used,saved,chosen);const m=melds[pos];if(!(used&m.mask)){const value=m.ids.reduce((s,i)=>s+cardPoints(hand[i]),0);chosen.push(m);dfs(pos+1,used|m.mask,saved+value,chosen);chosen.pop();}}dfs(0,0,0,[]);const deadwoodCards=hand.filter((_,i)=>!(best.used&(1<<i))),deadwood=deadwoodCards.reduce((s,c)=>s+cardPoints(c),0);const fullRun=hand.length===7&&melds.some(m=>m.type==="run"&&m.ids.length===7);return{deadwood,deadwoodCards,melds:best.chosen,chinchon:fullRun,total};}
  function combinations(arr,k){const out=[];function rec(start,p){if(p.length===k){out.push([...p]);return;}for(let i=start;i<arr.length;i++){p.push(arr[i]);rec(i+1,p);p.pop();}}rec(0,[]);return out;}
  function mask(ids){return ids.reduce((m,i)=>m|(1<<i),0);}
  function cardPoints(c){return c.rank>=10?10:c.rank;}
  function cardName(c){const name=c.rank===1?"as":c.rank===10?"sota":c.rank===11?"caballo":c.rank===12?"rey":String(c.rank);return `${name} de ${LABEL[c.suit]}`;}
  function cardImg(c){return `assets/cards/${c.suit}-${c.rank}.webp`;}
  function layOff(cards,melds){const loose=[...cards];let changed=true;while(changed){changed=false;for(let i=0;i<loose.length;i++){const card=loose[i],target=melds.find(m=>canAttach(card,m));if(!target)continue;target.cards.push(card);if(target.type==="run")target.cards.sort((a,b)=>RANKS.indexOf(a.rank)-RANKS.indexOf(b.rank));loose.splice(i,1);changed=true;break;}}return loose;}
  function canAttach(card,meld){if(meld.type==="group")return meld.cards.length<4&&meld.cards.every(c=>c.rank===card.rank);if(!meld.cards.length||meld.cards.some(c=>c.suit!==card.suit))return false;const positions=meld.cards.map(c=>RANKS.indexOf(c.rank));const pos=RANKS.indexOf(card.rank);return pos===Math.min(...positions)-1||pos===Math.max(...positions)+1;}
  function endRound(closerIndex){const closer=state.players[closerIndex],aClose=analysis(closer.hand);if(aClose.chinchon){finishMatch(closerIndex,"Chinchón de siete cartas");return;}const sharedMelds=aClose.melds.map(m=>({type:m.type,cards:m.ids.map(i=>closer.hand[i])}));const cleanClose=aClose.deadwood===0;const results=[];activeIndexes().forEach(i=>{const p=state.players[i],a=analysis(p.hand);let loose=[...a.deadwoodCards],laidOff=0;if(i!==closerIndex&&!cleanClose){const before=loose.length;loose=layOff(loose,sharedMelds);laidOff=before-loose.length;}const deadwood=loose.reduce((s,c)=>s+cardPoints(c),0),add=deadwood;if(i===closerIndex&&cleanClose)p.penalty=Math.max(0,p.penalty-10);else p.penalty+=add;if(p.penalty>=state.target)p.eliminated=true;results.push({i,name:p.name,deadwood,laidOff,add,penalty:p.penalty,eliminated:p.eliminated});});const alive=activeIndexes();UI.cRoundTitle.textContent=`${closer.name} cierra la ronda`;UI.cRoundResults.innerHTML=results.map(r=>`<div class="sg-score-row ${r.i===closerIndex?"active":""}"><span class="sg-avatar">${initials(r.name)}</span><div><strong>${escapeHtml(r.name)}</strong><small>${r.i===closerIndex?"Cierre válido":`${r.deadwood} puntos sueltos${r.laidOff?` · ${r.laidOff} colocada${r.laidOff===1?"":"s"}`:""}`}${r.eliminated?" · ELIMINADO":""}</small></div><b>${r.penalty}</b></div>`).join("");if(alive.length===1){state.winner=alive[0];UI.cNextRound.textContent="Ver resultado final";}else{state.dealer=nextActive(state.dealer);UI.cNextRound.textContent="Siguiente ronda";}state.phase="roundOver";save();render();UI.cRoundModal.showModal();}
  function nextRound(){UI.cRoundModal.close();if(state.winner!==null)finishMatch(state.winner,"Último jugador en mesa");else startRound();}
  function finishMatch(winnerIndex,reason){state.active=false;state.winner=winnerIndex;localStorage.removeItem(SAVE);const winner=state.players[winnerIndex],profile=state.players[0],won=state.mode==="solo"&&winnerIndex===0;window.SalaCeroClub?.recordMatch?.({game:"chinchon",mode:state.mode,local:state.mode==="local",won,score:Math.max(0,state.target-profile.penalty),opponentScore:state.mode==="solo"?Math.max(0,state.target-state.players[1].penalty):0,special:reason.includes("Chinchón")?"chinchon":""});UI.cRoundTitle.textContent=`${winner.name} gana la partida`;UI.cRoundResults.innerHTML=`<div class="sg-info-card"><span class="sg-card-title">RESULTADO FINAL</span><h3>${escapeHtml(reason)}</h3><p>${escapeHtml(winner.name)} termina como vencedor de la mesa.</p></div>`;UI.cNextRound.textContent="Nueva partida";UI.cNextRound.onclick=()=>location.reload();UI.cRoundModal.showModal();refreshContinue();}
  function render(){if(!state.active&&state.phase!=="roundOver")return;const p=current();UI.cTurnName.textContent=p?.name||"—";UI.cTurnKicker.textContent=p?.isAI?"TURNO DE LA IA":state.mode==="local"?"TURNO LOCAL":"TU TURNO";UI.cPhase.textContent=state.phase==="draw"?"ROBAR":state.phase==="discard"?"DESCARTAR":"RONDA CERRADA";UI.cStockCount.textContent=state.deck.length;const top=state.discard.at(-1);UI.cDiscardCard.innerHTML=top?`<img src="${cardImg(top)}" alt="${cardName(top)}">`:"";renderScores();renderOpponents();renderHand();renderAnalysis();UI.cStock.disabled=state.phase!=="draw"||p.isAI||!state.revealed;UI.cDiscard.disabled=state.phase!=="draw"||p.isAI||!state.revealed||!state.discard.length;UI.cDiscardBtn.disabled=state.phase!=="discard"||state.selected<0||p.isAI||!canDiscardIndex(state.selected);UI.cCloseBtn.disabled=state.phase!=="discard"||state.selected<0||p.isAI||!canCloseAfter(state.selected);UI.cMessage.textContent=!state.revealed?"Turno oculto.":p.isAI?"La IA está valorando su mano.":state.phase==="draw"?"Roba del mazo o toma la carta visible.":state.selected<0?"Selecciona la carta que quieres descartar.":!canDiscardIndex(state.selected)?"No puedes devolver inmediatamente la carta tomada del descarte.":UI.cCloseBtn.disabled?"Puedes descartar la carta seleccionada.":"Puedes descartar o cerrar la ronda.";UI.cLog.innerHTML=state.log.slice(-18).reverse().map(x=>`<div>${x}</div>`).join("");}
  function renderScores(){UI.cScores.innerHTML=state.players.map((p,i)=>`<div class="sg-score-row ${i===state.current?"active":""}"><span class="sg-avatar">${initials(p.name)}</span><div><strong>${escapeHtml(p.name)}</strong><small>${p.eliminated?"Eliminado":p.isAI?"IA":"Jugador"}</small></div><b>${p.penalty}</b></div>`).join("");}
  function renderOpponents(){const count=Math.max(0,...state.players.filter((_,i)=>i!==state.current&&!state.players[i].eliminated).map(p=>p.hand.length),0);UI.cOpponentHand.innerHTML=Array.from({length:count},()=>`<img src="assets/cards/back.svg" alt="Carta oculta">`).join("");}
  function renderHand(){UI.cHand.innerHTML="";if(!state.revealed||current().isAI)return;current().hand.forEach((c,i)=>{const b=document.createElement("button");const forbidden=state.phase==="discard"&&!canDiscardIndex(i);b.className=`sg-card ${state.selected===i?"selected":""} ${forbidden?"dim":""}`;b.style.setProperty("--card-index",i);b.draggable=true;b.innerHTML=`<img src="${cardImg(c)}" alt="${cardName(c)}">`;b.onclick=()=>{if(state.phase!=="discard")return;state.selected=i;render();};b.ondragstart=()=>dragIndex=i;b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();if(dragIndex===null||dragIndex===i)return;const [m]=current().hand.splice(dragIndex,1);current().hand.splice(i,0,m);state.selected=-1;dragIndex=null;render();save();};UI.cHand.appendChild(b);});}
  function renderAnalysis(){if(!state.revealed||current().isAI){UI.cHandStatus.textContent="Mano privada";UI.cHandAdvice.textContent="La información se mostrará durante tu turno.";return;}const a=analysis(current().hand);UI.cHandStatus.textContent=a.chinchon?"¡Chinchón preparado!":`${a.deadwood} puntos sueltos`;UI.cHandAdvice.textContent=a.melds.length?`${a.melds.length} combinación${a.melds.length===1?"":"es"} detectada${a.melds.length===1?"":"s"}. ${a.deadwoodCards.length?`Quedan sueltas: ${a.deadwoodCards.map(cardName).join(", ")}.`:"Toda la mano está ligada."}`:"Todavía no hay grupos o escaleras completos.";UI.cMeldTitle.textContent=a.chinchon?"Chinchón completo":(a.melds.length?`${a.melds.length} combinaciones`:"Sin combinaciones");UI.cMeldText.textContent=a.melds.map(m=>m.ids.map(i=>current().hand[i]).map(cardName).join(" · ")).join(" | ")||"Intenta conservar cartas consecutivas del mismo palo o números repetidos.";}
  function showHandoff(){if(state.mode!=="local"||!state.active)return;state.revealed=false;UI.cHandoffName.textContent=current().name;UI.cHandoff.classList.remove("hidden");render();}
  function revealTurn(){state.revealed=true;UI.cHandoff.classList.add("hidden");render();save();}
  function save(){if(!state.active)return;try{localStorage.setItem(SAVE,JSON.stringify(state));}catch(_){}}
  function continueGame(){try{const s=JSON.parse(localStorage.getItem(SAVE)||"null");if(!s?.active)return;Object.assign(state,s,{revealed:s.mode!=="local"});showGame();if(state.phase==="roundOver"){if(state.winner!==null)finishMatch(state.winner,"Partida recuperada");else startRound();return;}render();if(state.mode==="local")showHandoff();else maybeAI();}catch(_){localStorage.removeItem(SAVE);refreshContinue();}}
  function refreshContinue(){try{const s=JSON.parse(localStorage.getItem(SAVE)||"null"),ok=Boolean(s?.active);UI.cContinue.disabled=!ok;UI.cContinueTitle.textContent=ok?`Ronda ${s.round} · turno de ${s.players[s.current].name}`:"Sin partida pendiente";UI.cContinueMeta.textContent=ok?`${s.players.length} jugadores · límite ${s.target}.`:"El progreso se guarda después de cada robo y descarte.";}catch(_){UI.cContinue.disabled=true;}}
  function exitMenu(){save();UI.cGame.classList.add("hidden");UI.cWelcome.classList.remove("hidden");refreshContinue();}
  async function toggleMusic(){const a=document.getElementById("backgroundMusic");if(!a)return;if(a.paused){try{await a.play();localStorage.setItem("tuteIaMusicEnabled","true");UI.cMusic.textContent="♫";}catch(_){}}else{a.pause();localStorage.setItem("tuteIaMusicEnabled","false");UI.cMusic.textContent="♩";}window.TuteMusicContinuity?.savePosition();}
  function playCardSound(special=false){try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain(),n=ctx.currentTime;o.type="triangle";o.frequency.setValueAtTime(special?330:190,n);o.frequency.exponentialRampToValueAtTime(90,n+.09);g.gain.setValueAtTime(.045,n);g.gain.exponentialRampToValueAtTime(.0001,n+.1);o.connect(g).connect(ctx.destination);o.start(n);o.stop(n+.11);setTimeout(()=>ctx.close(),250);if(special)navigator.vibrate?.([40,30,80]);}catch(_){}}
  function toast(text){clearTimeout(toastTimer);UI.cToast.textContent=text;UI.cToast.classList.add("visible");toastTimer=setTimeout(()=>UI.cToast.classList.remove("visible"),1800);}
  function log(x){state.log.push(x);if(state.log.length>60)state.log.shift();}
  function initials(n){return n.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();}
  function wait(ms){return new Promise(r=>setTimeout(r,ms));}
  function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
  window.SalaCeroChinchonDebug={analysis,deck,cardPoints,layOff,canAttach,RANKS:[...RANKS],SUITS:[...SUITS]};
})();
