(() => {
  "use strict";
  const SUITS=["oros","copas","espadas","bastos"],RANKS=[1,2,3,4,5,6,7,10,11,12],ORDER=[3,4,5,6,7,10,11,12,1,2],SAVE="salaCeroCuloV201";
  const NAMES=["Don Prudencio","Lola Relámpago","El Tahúr","Doña Virtud","Maestro Cero"];
  const UI={},state={active:false,mode:"solo",players:[],round:0,targetRounds:5,current:0,trick:null,passes:0,finishOrder:[],selected:[],revealed:true,revolution:false,options:{twoClear:true,eightSkip:false,revolution:true},difficulty:"normal",log:[],rolesReady:false,awaitingNext:false};
  let toastTimer=null;
  document.addEventListener("DOMContentLoaded",init);
  function init(){cache();bind();const n=window.SalaCeroClub?.getData?.().profile?.name;if(n)UI.pName.value=n;renderNames();refreshContinue();const career=window.SalaCeroCareer?.getAiConfig?.("culo");if(career)startCareer(career);}
  function cache(){["pWelcome","pGame","pMusic","pSolo","pLocal","pContinue","pContinueTitle","pContinueMeta","pRules","pRulesModal","pRulesClose","pRulesOk","pSetup","pSetupForm","pSetupClose","pSetupTitle","pMode","pName","pRounds","pPlayerCount","pDifficultyField","pDifficulty","pLocalFields","pNames","pTwoClear","pEightSkip","pRevolution","pScorePanel","pScoreToggle","pScores","pTurnKicker","pTurnName","pPhase","pOpponents","pRankStrip","pTrick","pMessage","pClearSelection","pPass","pPlay","pHand","pRuleTitle","pRuleText","pLog","pExit","pHandoff","pHandoffName","pReveal","pRoundModal","pRoundTitle","pRoundResults","pNextRound","pToast"].forEach(id=>UI[id]=document.getElementById(id));}
  function bind(){UI.pSolo.onclick=()=>openSetup("solo");UI.pLocal.onclick=()=>openSetup("local");UI.pContinue.onclick=continueGame;UI.pMusic.onclick=toggleMusic;UI.pRules.onclick=()=>UI.pRulesModal.showModal();UI.pRulesClose.onclick=UI.pRulesOk.onclick=()=>UI.pRulesModal.close();UI.pSetupClose.onclick=()=>UI.pSetup.close();UI.pPlayerCount.onchange=renderNames;UI.pSetupForm.onsubmit=e=>{e.preventDefault();startFromSetup();};UI.pClearSelection.onclick=()=>{state.selected=[];render();};UI.pPass.onclick=humanPass;UI.pPlay.onclick=humanPlay;UI.pExit.onclick=exitMenu;UI.pReveal.onclick=revealTurn;UI.pScoreToggle.onclick=()=>UI.pScorePanel.classList.toggle("expanded");UI.pNextRound.onclick=nextRound;document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.active&&state.mode==="local"&&state.revealed)showHandoff();});}
  function openSetup(mode){UI.pMode.value=mode;UI.pSetupTitle.textContent=mode==="solo"?"Partida contra la mesa":"Partida local";UI.pLocalFields.classList.toggle("hidden",mode!=="local");UI.pDifficultyField.classList.toggle("hidden",mode!=="solo");renderNames();UI.pSetup.showModal();}
  function renderNames(){const count=Number(UI.pPlayerCount?.value||4);UI.pNames.innerHTML="";for(let i=0;i<count;i++){const l=document.createElement("label");l.className="sg-field";l.innerHTML=`<span>Jugador ${i+1}</span><input id="pLocalName${i}" maxlength="18" value="${i===0?escapeHtml(UI.pName?.value||"Jugador"):`Jugador ${i+1}`}">`;UI.pNames.appendChild(l);}}
  function startFromSetup(){const mode=UI.pMode.value,count=Number(UI.pPlayerCount.value),profile=window.SalaCeroClub?.getData?.().profile?.name||"Jugador";const players=Array.from({length:count},(_,i)=>({name:mode==="solo"?(i===0?(UI.pName.value.trim()||profile):NAMES[(i-1)%NAMES.length]):(document.getElementById(`pLocalName${i}`)?.value.trim()||`Jugador ${i+1}`),isAI:mode==="solo"&&i>0,hand:[],prestige:0,role:"Sin rango",finished:false}));Object.assign(state,{active:true,mode,players,round:0,targetRounds:Number(UI.pRounds.value),current:0,trick:null,passes:0,finishOrder:[],selected:[],revealed:mode!=="local",revolution:false,options:{twoClear:UI.pTwoClear.checked,eightSkip:UI.pEightSkip.checked,revolution:UI.pRevolution.checked},difficulty:UI.pDifficulty.value||"normal",log:[],rolesReady:false,awaitingNext:false});UI.pSetup.close();showGame();startRound();}
  function startCareer(cfg){const name=window.SalaCeroClub?.getData?.().profile?.name||"Jugador";const players=[{name,isAI:false,hand:[],prestige:0,role:"Sin rango",finished:false},{name:cfg.name||"Maestro Cero",isAI:true,hand:[],prestige:0,role:"Sin rango",finished:false},{name:"El Tahúr",isAI:true,hand:[],prestige:0,role:"Sin rango",finished:false},{name:"Doña Virtud",isAI:true,hand:[],prestige:0,role:"Sin rango",finished:false}];Object.assign(state,{active:true,mode:"solo",players,round:0,targetRounds:3,current:0,trick:null,passes:0,finishOrder:[],selected:[],revealed:true,revolution:false,options:{twoClear:true,eightSkip:false,revolution:true},difficulty:cfg.difficulty||"hard",log:[`Encuentro de carrera: ${cfg.matchLabel||cfg.competitionTitle}.`],rolesReady:false,awaitingNext:false});showGame();startRound();}
  function showGame(){UI.pWelcome.classList.add("hidden");UI.pGame.classList.remove("hidden");window.scrollTo(0,0);}
  function deck(){return SUITS.flatMap(s=>RANKS.map(r=>({id:`${s}-${r}`,suit:s,rank:r})));}
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function startRound(){state.awaitingNext=false;state.round++;state.trick=null;state.passes=0;state.finishOrder=[];state.selected=[];state.revolution=false;state.players.forEach(p=>{p.hand=[];p.finished=false;});const d=shuffle(deck()),start=state.rolesReady?state.players.findIndex(p=>p.role==="Culo"):0;for(let i=0;d.length;i++)state.players[(start+i)%state.players.length].hand.push(d.pop());if(state.rolesReady)exchangeCards();state.current=state.rolesReady?Math.max(0,state.players.findIndex(p=>p.role==="Culo")):holderOfThreeGold();sortAll();state.revealed=state.mode!=="local";log(`Mano ${state.round}: ${state.players[state.current].name} abre la mesa.`);render();save();if(state.mode==="local")showHandoff();else maybeAI();}
  function holderOfThreeGold(){const i=state.players.findIndex(p=>p.hand.some(c=>c.suit==="oros"&&c.rank===3));return i>=0?i:0;}
  function sortAll(){state.players.forEach(p=>p.hand.sort((a,b)=>strength(a.rank)-strength(b.rank)||SUITS.indexOf(a.suit)-SUITS.indexOf(b.suit)));}
  function exchangeCards(){const pres=state.players.find(p=>p.role==="Presidente"),culo=state.players.find(p=>p.role==="Culo");if(pres&&culo){pres.hand.sort((a,b)=>strength(a.rank)-strength(b.rank));culo.hand.sort((a,b)=>strength(a.rank)-strength(b.rank));const low=pres.hand.splice(0,Math.min(2,pres.hand.length)),high=culo.hand.splice(Math.max(0,culo.hand.length-2));pres.hand.push(...high);culo.hand.push(...low);log("Presidente y Culo intercambian dos cartas.");}const vice=state.players.find(p=>p.role==="Vicepresidente"),viceculo=state.players.find(p=>p.role==="Viceculo");if(vice&&viceculo){vice.hand.sort((a,b)=>strength(a.rank)-strength(b.rank));viceculo.hand.sort((a,b)=>strength(a.rank)-strength(b.rank));const low=vice.hand.shift(),high=viceculo.hand.pop();if(high)vice.hand.push(high);if(low)viceculo.hand.push(low);log("Vicepresidente y Viceculo intercambian una carta.");}}
  function strength(rank){const base=ORDER.indexOf(rank);return state.revolution?ORDER.length-1-base:base;}
  function current(){return state.players[state.current];}
  function activeIndexes(){return state.players.map((p,i)=>!p.finished?i:null).filter(i=>i!==null);}
  function nextActive(from,steps=1){let i=from;for(let s=0;s<steps;s++){do{i=(i+1)%state.players.length;}while(state.players[i].finished);}return i;}
  function toggleCard(index){if(!state.active||!state.revealed||current().isAI||current().finished)return;const already=state.selected.includes(index);if(already)state.selected=state.selected.filter(i=>i!==index);else{const rank=current().hand[index]?.rank;if(state.selected.length&&current().hand[state.selected[0]]?.rank!==rank)state.selected=[];state.selected.push(index);}render();}
  function selectedCards(){return state.selected.map(i=>current().hand[i]).filter(Boolean);}
  function isLegal(cards){if(!cards.length)return false;if(cards.some(c=>c.rank!==cards[0].rank))return false;if(!state.trick)return true;return cards.length===state.trick.count&&strength(cards[0].rank)>strength(state.trick.rank);}
  function humanPlay(){if(!state.revealed||current().isAI||!isLegal(selectedCards()))return;playSelected([...state.selected]);}
  function playSelected(indexes){const p=current(),cards=indexes.sort((a,b)=>b-a).map(i=>p.hand.splice(i,1)[0]).reverse();const rank=cards[0].rank;state.trick={rank,count:cards.length,cards,lastPlayer:state.current};state.passes=0;state.selected=[];playSound();log(`${p.name} juega ${cards.length>1?`${cards.length} cartas de ${rankLabel(rank)}`:cardName(cards[0])}.`);if(state.options.revolution&&cards.length===4){state.revolution=!state.revolution;toast(state.revolution?"¡Revolución! El orden se invierte":"La revolución termina");log("Cuatro iguales cambian el orden de fuerza.");}if(!p.hand.length)markFinished(state.current);if(activeIndexes().length<=1){finishRound();return;}if(state.options.twoClear&&rank===2){toast("El 2 limpia la mesa");clearTrick(state.current);return;}let steps=1;if(state.options.eightSkip&&rank===10&&activeIndexes().length>2){steps=2;toast("La sota salta un turno");}state.current=nextActive(state.current,steps);state.revealed=state.mode!=="local";render();save();if(state.mode==="local")showHandoff();else maybeAI();}
  function humanPass(){if(!state.revealed||current().isAI||!state.trick)return;passTurn();}
  function passTurn(){const p=current();state.passes++;log(`${p.name} pasa.`);const active=activeIndexes(),lastStill=active.includes(state.trick?.lastPlayer),needed=active.length-(lastStill?1:0);if(state.passes>=needed){clearTrick(state.trick?.lastPlayer??state.current);return;}state.current=nextActive(state.current);state.revealed=state.mode!=="local";render();save();if(state.mode==="local")showHandoff();else maybeAI();}
  function clearTrick(last){state.trick=null;state.passes=0;const active=activeIndexes();if(active.length<=1){finishRound();return;}state.current=active.includes(last)?last:nextActive(last);state.revealed=state.mode!=="local";log(`${state.players[state.current].name} limpia y vuelve a abrir.`);render();save();if(state.mode==="local")showHandoff();else maybeAI();}
  function markFinished(index){if(state.players[index].finished)return;state.players[index].finished=true;state.finishOrder.push(index);toast(`${state.players[index].name} termina en posición ${state.finishOrder.length}`);}
  async function maybeAI(){if(!state.active||!current().isAI||current().finished)return;await wait(560);const groups=legalGroups(current().hand);if(!groups.length){passTurn();return;}let choice=groups[0];if(state.difficulty==="easy"&&Math.random()<.32)choice=groups[Math.floor(Math.random()*groups.length)];if(state.difficulty==="hard"){const twos=groups.filter(g=>g.cards[0].rank===2);if(twos.length&&state.trick&&Math.random()<.25)choice=twos[0];else choice=groups[0];}playSelected(choice.indexes);}
  function legalGroups(hand){const by={};hand.forEach((c,i)=>(by[c.rank]??=[]).push(i));const groups=[];Object.entries(by).forEach(([rank,ids])=>{const r=Number(rank);const counts=state.trick?[state.trick.count]:[Math.min(ids.length,1),2,3,4].filter(n=>n<=ids.length);counts.forEach(n=>{if(!state.trick||strength(r)>strength(state.trick.rank))groups.push({indexes:ids.slice(0,n),cards:ids.slice(0,n).map(i=>hand[i])});});});return groups.sort((a,b)=>strength(a.cards[0].rank)-strength(b.cards[0].rank)||b.cards.length-a.cards.length);}
  function finishRound(){const remaining=activeIndexes();remaining.forEach(i=>markFinished(i));assignRoles();state.rolesReady=true;const rows=state.finishOrder.map((idx,pos)=>{const p=state.players[idx],delta=prestigeFor(pos,state.players.length);p.prestige+=delta;return{p,pos,delta};});UI.pRoundTitle.textContent=`Cargos de la mano ${state.round}`;UI.pRoundResults.innerHTML=rows.map(({p,pos,delta})=>`<div class="sg-score-row"><span class="sg-avatar">${pos+1}</span><div><strong>${escapeHtml(p.name)}</strong><small>${p.role}</small></div><b>${delta>=0?"+":""}${delta}</b></div>`).join("");UI.pNextRound.textContent=state.round>=state.targetRounds?"Ver resultado final":"Siguiente mano";state.awaitingNext=true;state.active=true;save();render();UI.pRoundModal.showModal();}
  function assignRoles(){const n=state.finishOrder.length;state.finishOrder.forEach((idx,pos)=>{let role="Neutral";if(pos===0)role="Presidente";else if(n>=4&&pos===1)role="Vicepresidente";else if(pos===n-1)role="Culo";else if(n>=4&&pos===n-2)role="Viceculo";state.players[idx].role=role;});}
  function prestigeFor(pos,n){if(pos===0)return 3;if(n>=4&&pos===1)return 2;if(pos===n-1)return-1;if(n>=4&&pos===n-2)return 0;return 1;}
  function nextRound(){UI.pRoundModal.close();state.awaitingNext=false;if(state.round>=state.targetRounds){finishMatch();return;}startRound();}
  function finishMatch(){state.active=false;localStorage.removeItem(SAVE);const max=Math.max(...state.players.map(p=>p.prestige)),winners=state.players.filter(p=>p.prestige===max),winner=winners[0],won=state.mode==="solo"&&state.players[0].prestige===max&&winners.length===1;window.SalaCeroClub?.recordMatch?.({game:"culo",mode:state.mode,local:state.mode==="local",won,score:state.players[0].prestige,opponentScore:Math.max(...state.players.slice(1).map(p=>p.prestige)),special:state.players[0].role==="Presidente"?"president":""});UI.pRoundModal.showModal();UI.pRoundTitle.textContent=winners.length===1?`${winner.name} conquista la mesa`:"Empate de prestigio";UI.pRoundResults.innerHTML=state.players.slice().sort((a,b)=>b.prestige-a.prestige).map((p,i)=>`<div class="sg-score-row"><span class="sg-avatar">${i+1}</span><div><strong>${escapeHtml(p.name)}</strong><small>${p.role}</small></div><b>${p.prestige}</b></div>`).join("");UI.pNextRound.textContent="Nueva partida";UI.pNextRound.onclick=()=>location.reload();refreshContinue();}
  function render(){if(!state.players.length)return;const p=current();UI.pTurnName.textContent=p.name;UI.pTurnKicker.textContent=p.isAI?"TURNO DE LA IA":state.mode==="local"?"TURNO LOCAL":"TU TURNO";UI.pPhase.textContent=state.trick?`${state.trick.count} × ${rankLabel(state.trick.rank)}`:"ABRE LA MESA";renderScores();renderOpponents();renderRanks();renderTrick();renderHand();UI.pPass.disabled=!state.trick||p.isAI||!state.revealed;UI.pPlay.disabled=p.isAI||!state.revealed||!isLegal(selectedCards());UI.pClearSelection.disabled=!state.selected.length;UI.pMessage.textContent=message();UI.pRuleTitle.textContent=state.revolution?"Revolución activa":"Mismo número de cartas";UI.pRuleText.textContent=state.revolution?"El orden está invertido: ahora ganan los valores normalmente más bajos.":state.trick?`Debes jugar ${state.trick.count} carta${state.trick.count>1?"s":""} iguales por encima de ${rankLabel(state.trick.rank)}, o pasar.`:"Puedes abrir con una, dos, tres o cuatro cartas iguales.";UI.pLog.innerHTML=state.log.slice(-18).reverse().map(x=>`<div>${x}</div>`).join("");}
  function renderScores(){UI.pScores.innerHTML=state.players.map((p,i)=>`<div class="sg-score-row ${i===state.current?"active":""}"><span class="sg-avatar">${initials(p.name)}</span><div><strong>${escapeHtml(p.name)}</strong><small>${p.role} · ${p.hand.length} cartas</small></div><b>${p.prestige}</b></div>`).join("");}
  function renderOpponents(){UI.pOpponents.innerHTML=state.players.map((p,i)=>`<div class="culo-opponent ${i===state.current?"active":""} ${p.finished?"finished":""}"><span>${initials(p.name)}</span><div><strong>${escapeHtml(p.name)}</strong><small>${p.finished?p.role:`${p.hand.length} cartas`}</small></div></div>`).join("");}
  function renderRanks(){UI.pRankStrip.classList.toggle("reversed",state.revolution);UI.pRankStrip.innerHTML=ORDER.map((r,i)=>`<span class="${(!state.revolution&&i===ORDER.length-1)||(state.revolution&&i===0)?"high":""}">${rankLabel(r)}</span>`).join("");}
  function renderTrick(){if(!state.trick){UI.pTrick.innerHTML="<span>Mesa limpia</span>";return;}UI.pTrick.innerHTML=state.trick.cards.map(c=>`<img src="${img(c)}" alt="${cardName(c)}">`).join("");}
  function renderHand(){UI.pHand.innerHTML="";if(!state.revealed||current().isAI||current().finished)return;current().hand.forEach((c,i)=>{const b=document.createElement("button"),same=!state.selected.length||current().hand[state.selected[0]]?.rank===c.rank;b.className=`sg-card ${state.selected.includes(i)?"selected":""} ${same?"":"illegal"}`;b.style.setProperty("--card-index",i);b.innerHTML=`<img src="${img(c)}" alt="${cardName(c)}">`;b.onclick=()=>toggleCard(i);UI.pHand.appendChild(b);});}
  function message(){if(!state.revealed)return"Turno oculto.";if(current().isAI)return"La IA está valorando si superar la mesa o pasar.";if(current().finished)return"Ya has terminado esta mano.";if(!state.trick)return"Abre con una o varias cartas iguales.";const legal=legalGroups(current().hand);return legal.length?"Selecciona una combinación superior o pasa.":"No tienes una respuesta legal: debes pasar.";}
  function showHandoff(){if(state.mode!=="local"||!state.active||current().finished)return;state.revealed=false;state.selected=[];UI.pHandoffName.textContent=current().name;UI.pHandoff.classList.remove("hidden");render();}
  function revealTurn(){state.revealed=true;UI.pHandoff.classList.add("hidden");render();save();}
  function save(){if(!state.players.length)return;try{localStorage.setItem(SAVE,JSON.stringify(state));}catch(_){} }
  function continueGame(){try{const s=JSON.parse(localStorage.getItem(SAVE)||"null");if(!s?.players?.length)return;Object.assign(state,s,{revealed:s.mode!=="local",selected:[]});showGame();if(state.awaitingNext){if(state.round>=state.targetRounds)finishMatch();else startRound();return;}render();if(state.mode==="local")showHandoff();else maybeAI();}catch(_){localStorage.removeItem(SAVE);refreshContinue();}}
  function refreshContinue(){try{const s=JSON.parse(localStorage.getItem(SAVE)||"null"),ok=Boolean(s?.players?.length&&s.round<=s.targetRounds);UI.pContinue.disabled=!ok;UI.pContinueTitle.textContent=ok?(s.awaitingNext?`Mano ${s.round} terminada`:`Mano ${s.round} · turno de ${s.players[s.current].name}`):"Sin partida pendiente";UI.pContinueMeta.textContent=ok?`${s.players.length} jugadores · ${s.targetRounds} manos.`:"La mesa se guarda después de cada jugada.";}catch(_){UI.pContinue.disabled=true;}}
  function exitMenu(){save();UI.pGame.classList.add("hidden");UI.pWelcome.classList.remove("hidden");refreshContinue();}
  async function toggleMusic(){const a=document.getElementById("backgroundMusic");if(!a)return;if(a.paused){try{await a.play();localStorage.setItem("tuteIaMusicEnabled","true");UI.pMusic.textContent="♫";}catch(_){}}else{a.pause();localStorage.setItem("tuteIaMusicEnabled","false");UI.pMusic.textContent="♩";}window.TuteMusicContinuity?.savePosition();}
  function playSound(){try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain(),n=ctx.currentTime;o.type="triangle";o.frequency.setValueAtTime(230,n);o.frequency.exponentialRampToValueAtTime(90,n+.09);g.gain.setValueAtTime(.04,n);g.gain.exponentialRampToValueAtTime(.0001,n+.1);o.connect(g).connect(ctx.destination);o.start(n);o.stop(n+.11);setTimeout(()=>ctx.close(),220);}catch(_){} }
  function img(c){return`assets/cards/${c.suit}-${c.rank}.webp`;}
  function rankLabel(r){return({1:"As",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",10:"Sota",11:"Caballo",12:"Rey"})[r]||String(r);}
  function cardName(c){return`${rankLabel(c.rank)} de ${c.suit}`;}
  function toast(text){clearTimeout(toastTimer);UI.pToast.textContent=text;UI.pToast.classList.add("visible");toastTimer=setTimeout(()=>UI.pToast.classList.remove("visible"),1800);}
  function log(x){state.log.push(x);if(state.log.length>70)state.log.shift();}
  function initials(n){return n.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();}
  function wait(ms){return new Promise(r=>setTimeout(r,ms));}
  function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);}
  window.SalaCeroCuloDebug={deck,ORDER:[...ORDER],isLegal:(cards,trick,revolution=false)=>{const oldT=state.trick,oldR=state.revolution;state.trick=trick;state.revolution=revolution;const result=isLegal(cards);state.trick=oldT;state.revolution=oldR;return result;}};
})();
