(() => {
  "use strict";
  const SUITS=["oros","copas","espadas","bastos"],RANKS=[1,2,3,4,5,6,7,10,11,12],SAVE="salaCeroEscobaV20";
  let toastTimer=null;
  const UI={},state={active:false,mode:"solo",target:15,players:[],dealer:0,current:0,deck:[],table:[],selectedHand:-1,selectedTable:[],lastCapture:null,handNo:0,revealed:true,log:[],winner:null,aiStyle:"unpredictable",aiDifficulty:"normal"};
  document.addEventListener("DOMContentLoaded",init);
  function init(){cache();bind();const n=window.SalaCeroClub?.getData?.().profile?.name;if(n)UI.eName.value=n;renderNames();refreshContinue();const career=window.SalaCeroCareer?.getAiConfig?.("escoba");if(career)startCareer(career);}
  function cache(){["eWelcome","eGame","eMusic","eSolo","eLocal","eContinue","eContinueTitle","eContinueMeta","eRules","eRulesModal","eRulesClose","eRulesOk","eSetup","eSetupForm","eSetupClose","eSetupTitle","eMode","eName","eTarget","eDifficultyField","eDifficulty","eLocalFields","ePlayerCount","eNames","eScorePanel","eScoreToggle","eScores","eTurnKicker","eTurnName","eDeckInfo","eOpponentHand","eTableCards","eMessage","eCombos","eLeave","eCapture","eHand","eAdviceTitle","eAdvice","eLog","eExit","eHandoff","eHandoffName","eReveal","eRoundModal","eRoundTitle","eRoundResults","eNextRound","eToast"].forEach(id=>UI[id]=document.getElementById(id));}
  function bind(){UI.eSolo.onclick=()=>openSetup("solo");UI.eMusic.onclick=toggleMusic;UI.eLocal.onclick=()=>openSetup("local");UI.eContinue.onclick=continueGame;UI.eRules.onclick=()=>UI.eRulesModal.showModal();UI.eRulesClose.onclick=UI.eRulesOk.onclick=()=>UI.eRulesModal.close();UI.eSetupClose.onclick=()=>UI.eSetup.close();UI.ePlayerCount.onchange=renderNames;UI.eSetupForm.onsubmit=e=>{e.preventDefault();startFromSetup();};UI.eLeave.onclick=()=>playSelected([]);UI.eCapture.onclick=()=>playSelected(state.selectedTable);UI.eExit.onclick=exitMenu;UI.eReveal.onclick=revealTurn;UI.eScoreToggle.onclick=()=>UI.eScorePanel.classList.toggle("expanded");UI.eNextRound.onclick=nextHand;document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.active&&state.mode==="local"&&state.revealed)showHandoff();});}
  function openSetup(mode){UI.eMode.value=mode;UI.eSetupTitle.textContent=mode==="solo"?"Partida contra El Tahúr":"Partida local";UI.eLocalFields.classList.toggle("hidden",mode!=="local");UI.eDifficultyField.classList.toggle("hidden",mode!=="solo");renderNames();UI.eSetup.showModal();}
  function renderNames(){const count=Number(UI.ePlayerCount?.value||2);UI.eNames.innerHTML="";for(let i=0;i<count;i++){const l=document.createElement("label");l.className="sg-field";l.innerHTML=`<span>Jugador ${i+1}</span><input id="eLocalName${i}" maxlength="18" value="${i===0?escapeHtml(UI.eName?.value||"Jugador"):`Jugador ${i+1}`}">`;UI.eNames.appendChild(l);}}
  function startFromSetup(){const mode=UI.eMode.value,count=mode==="solo"?2:Number(UI.ePlayerCount.value),club=window.SalaCeroClub?.getData?.().profile?.name||"Jugador";const players=Array.from({length:count},(_,i)=>({name:mode==="solo"?(i===0?(UI.eName.value.trim()||club):"El Tahúr"):(document.getElementById(`eLocalName${i}`)?.value.trim()||`Jugador ${i+1}`),isAI:mode==="solo"&&i===1,points:0,hand:[],captured:[],escobas:0}));Object.assign(state,{active:true,mode,target:Number(UI.eTarget.value),players,dealer:0,current:0,deck:[],table:[],selectedHand:-1,selectedTable:[],lastCapture:null,handNo:0,revealed:mode!=="local",log:[],winner:null,aiStyle:"unpredictable",aiDifficulty:UI.eDifficulty.value||"normal"});UI.eSetup.close();showGame();startHand();}
  function startCareer(cfg){const name=window.SalaCeroClub?.getData?.().profile?.name||"Jugador";Object.assign(state,{active:true,mode:"solo",target:11,players:[{name,isAI:false,points:0,hand:[],captured:[],escobas:0},{name:cfg.name||"El Tahúr",isAI:true,points:0,hand:[],captured:[],escobas:0}],dealer:0,current:0,deck:[],table:[],selectedHand:-1,selectedTable:[],lastCapture:null,handNo:0,revealed:true,log:[`Encuentro de carrera: ${cfg.matchLabel||cfg.competitionTitle}.`],winner:null,aiStyle:cfg.personality||"unpredictable",aiDifficulty:cfg.difficulty||"normal"});showGame();startHand();}
  function showGame(){UI.eWelcome.classList.add("hidden");UI.eGame.classList.remove("hidden");window.scrollTo(0,0);}
  function deck(){return SUITS.flatMap(s=>RANKS.map(r=>({id:`${s}-${r}`,suit:s,rank:r})));}
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function startHand(){state.handNo++;state.deck=shuffle(deck());state.table=[];state.lastCapture=null;state.selectedHand=-1;state.selectedTable=[];state.players.forEach(p=>{p.hand=[];p.captured=[];p.escobas=0;});dealThree();for(let i=0;i<4;i++)state.table.push(state.deck.pop());const count=initialEscobas(state.table);if(count){const dealer=state.players[state.dealer];dealer.captured.push(...state.table);dealer.escobas+=count;state.table=[];state.lastCapture=state.dealer;log(`${dealer.name} consigue ${count===2?"dos escobas":"una escoba"} en el reparto inicial.`);}state.current=next(state.dealer);state.revealed=state.mode!=="local";log(`Mano ${state.handNo}: reparte ${state.players[state.dealer].name}.`);render();save();if(state.mode==="local")showHandoff();else maybeAI();}
  function dealThree(){for(let n=0;n<3;n++)state.players.forEach(p=>{if(state.deck.length)p.hand.push(state.deck.pop());});}
  function next(i){return(i+1)%state.players.length;}
  function current(){return state.players[state.current];}
  function value(c){return c.rank===10?8:c.rank===11?9:c.rank===12?10:c.rank;}
  function initialEscobas(cards){const sum=cards.reduce((s,c)=>s+value(c),0);return sum===15?1:sum===30?2:0;}
  function cardName(c){const n=c.rank===1?"as":c.rank===10?"sota":c.rank===11?"caballo":c.rank===12?"rey":String(c.rank);return`${n} de ${c.suit}`;}
  function img(c){return`assets/cards/${c.suit}-${c.rank}.webp`;}
  function selectHand(i){if(!state.revealed||current().isAI)return;state.selectedHand=i;state.selectedTable=[];render();}
  function combosFor(card,table=state.table){const target=15-value(card),out=[];function rec(pos,sum,ids){if(sum===target&&ids.length){out.push([...ids]);return;}if(sum>=target)return;for(let i=pos;i<table.length;i++){ids.push(i);rec(i+1,sum+value(table[i]),ids);ids.pop();}}if(target>0)rec(0,0,[]);return out;}
  function toggleTable(i){if(state.selectedHand<0)return;const p=state.selectedTable.indexOf(i);if(p>=0)state.selectedTable.splice(p,1);else state.selectedTable.push(i);state.selectedTable.sort((a,b)=>a-b);render();}
  function validSelection(){if(state.selectedHand<0||!state.selectedTable.length)return false;return value(current().hand[state.selectedHand])+state.selectedTable.reduce((s,i)=>s+value(state.table[i]),0)===15;}
  function playSelected(indices){if(state.selectedHand<0||current().isAI||!state.revealed)return;const combos=combosFor(current().hand[state.selectedHand]);if(indices.length&&!validSelection())return;if(!indices.length&&combos.length)return;playMove(state.selectedHand,indices);}
  function playMove(handIndex,indices){const p=current(),card=p.hand.splice(handIndex,1)[0];playCardSound(indices.length>0);if(indices.length){const caught=indices.sort((a,b)=>b-a).map(i=>state.table.splice(i,1)[0]).reverse();p.captured.push(card,...caught);state.lastCapture=state.current;const escoba=state.table.length===0;if(escoba){p.escobas++;toast("¡ESCOBA!");navigator.vibrate?.([50,30,90]);}log(`${p.name} captura ${caught.map(cardName).join(", ")}${escoba?" y hace ESCOBA":""}.`);}else{state.table.push(card);log(`${p.name} deja ${cardName(card)} en la mesa.`);}state.selectedHand=-1;state.selectedTable=[];advanceTurn();}
  function advanceTurn(){const handsEmpty=state.players.every(p=>p.hand.length===0);if(handsEmpty){if(state.deck.length){dealThree();log("Se reparten tres cartas nuevas.");state.current=next(state.current);state.revealed=state.mode!=="local";render();save();if(state.mode==="local")showHandoff();else maybeAI();return;}endHand();return;}state.current=next(state.current);state.revealed=state.mode!=="local";render();save();if(state.mode==="local")showHandoff();else maybeAI();}
  async function maybeAI(){if(!state.active||!current().isAI)return;await wait(650);let move=bestMove(current());if((state.aiDifficulty==="easy"||state.aiStyle==="unpredictable")&&Math.random()<.26)move=randomMove(current());state.selectedHand=move.handIndex;state.selectedTable=move.indices;render();await wait(650);playMove(move.handIndex,move.indices);}
  function bestMove(p){let best=null;p.hand.forEach((card,hi)=>{const combos=combosFor(card);if(!combos.length){const score=-discardRisk(card);const move={handIndex:hi,indices:[],score};if(!best||score>best.score)best=move;}combos.forEach(ids=>{const caught=ids.map(i=>state.table[i]),clears=ids.length===state.table.length;let score=ids.length*5+(clears?40:0);if(card.suit==="oros")score+=3;if(card.rank===7)score+=5;if(card.suit==="oros"&&card.rank===7)score+=30;caught.forEach(c=>{if(c.suit==="oros")score+=3;if(c.rank===7)score+=5;if(c.suit==="oros"&&c.rank===7)score+=30;});const move={handIndex:hi,indices:ids,score};if(!best||score>best.score)best=move;});});return best||{handIndex:0,indices:[],score:0};}
  function discardRisk(c){return(c.suit==="oros"?8:0)+(c.rank===7?10:0)+(c.suit==="oros"&&c.rank===7?30:0)+value(c);}
  function randomMove(p){const handIndex=Math.floor(Math.random()*p.hand.length),options=combosFor(p.hand[handIndex]);return{handIndex,indices:options.length?options[Math.floor(Math.random()*options.length)]:[],score:0};}
  function endHand(){const receiver=state.lastCapture??state.dealer;if(state.table.length){state.players[receiver].captured.push(...state.table);log(`${state.players[receiver].name} recoge las cartas restantes.`);state.table=[];}const stats=state.players.map((p,i)=>({i,cards:p.captured.length,oros:p.captured.filter(c=>c.suit==="oros").length,sevens:p.captured.filter(c=>c.rank===7).length,sevenGold:p.captured.some(c=>c.suit==="oros"&&c.rank===7),escobas:p.escobas,add:p.escobas}));awardMajority(stats,"cards");awardMajority(stats,"oros");awardMajority(stats,"sevens");stats.forEach(s=>{if(s.sevenGold)s.add++;state.players[s.i].points+=s.add;});const max=Math.max(...state.players.map(p=>p.points)),leaders=state.players.map((p,i)=>p.points===max?i:null).filter(i=>i!==null);if(max>=state.target&&leaders.length===1)state.winner=leaders[0];UI.eRoundTitle.textContent=`Recuento de la mano ${state.handNo}`;UI.eRoundResults.innerHTML=stats.map(s=>`<div class="sg-score-row"><span class="sg-avatar">${initials(state.players[s.i].name)}</span><div><strong>${escapeHtml(state.players[s.i].name)}</strong><small>${s.escobas} escobas · ${s.cards} cartas · ${s.oros} oros · ${s.sevens} sietes${s.sevenGold?" · siete de oros":""}</small></div><b>+${s.add}</b></div>`).join("");UI.eNextRound.textContent=state.winner===null?"Siguiente mano":"Ver resultado final";state.dealer=next(state.dealer);save();render();UI.eRoundModal.showModal();}
  function awardMajority(stats,key){const m=Math.max(...stats.map(s=>s[key]));const winners=stats.filter(s=>s[key]===m);if(winners.length===1)winners[0].add++;}
  function nextHand(){UI.eRoundModal.close();if(state.winner!==null)finishMatch(state.winner);else startHand();}
  function finishMatch(winnerIndex){state.active=false;localStorage.removeItem(SAVE);const winner=state.players[winnerIndex],profile=state.players[0],won=state.mode==="solo"&&winnerIndex===0;window.SalaCeroClub?.recordMatch?.({game:"escoba",mode:state.mode,local:state.mode==="local",won,score:profile.points,opponentScore:state.mode==="solo"?state.players[1].points:0,special:profile.escobas>=3?"escobas":""});UI.eRoundTitle.textContent=`${winner.name} gana la partida`;UI.eRoundResults.innerHTML=`<div class="sg-info-card"><span class="sg-card-title">RESULTADO FINAL</span><h3>${winner.points} puntos</h3><p>${escapeHtml(winner.name)} alcanza el objetivo de ${state.target} puntos.</p></div>`;UI.eNextRound.textContent="Nueva partida";UI.eNextRound.onclick=()=>location.reload();UI.eRoundModal.showModal();refreshContinue();}
  function render(){if(!state.players.length)return;const p=current();UI.eTurnName.textContent=p.name;UI.eTurnKicker.textContent=p.isAI?"TURNO DE LA IA":state.mode==="local"?"TURNO LOCAL":"TU TURNO";UI.eDeckInfo.textContent=`Mazo ${state.deck.length}`;renderScores();renderOpponents();renderTable();renderHand();renderCombos();UI.eLog.innerHTML=state.log.slice(-18).reverse().map(x=>`<div>${x}</div>`).join("");}
  function renderScores(){UI.eScores.innerHTML=state.players.map((p,i)=>`<div class="sg-score-row ${i===state.current?"active":""}"><span class="sg-avatar">${initials(p.name)}</span><div><strong>${escapeHtml(p.name)}</strong><small>${p.escobas} escobas · ${p.captured.length} capturas</small></div><b>${p.points}</b></div>`).join("");}
  function renderOpponents(){const count=Math.max(0,...state.players.filter((_,i)=>i!==state.current).map(p=>p.hand.length),0);UI.eOpponentHand.innerHTML=Array.from({length:count},()=>`<img src="assets/cards/back.svg" alt="Carta oculta">`).join("");}
  function renderTable(){UI.eTableCards.innerHTML="";state.table.forEach((c,i)=>{const b=document.createElement("button");b.className=`sg-card ${state.selectedTable.includes(i)?"chosen":""}`;b.style.setProperty("--card-index",i);b.innerHTML=`<img src="${img(c)}" alt="${cardName(c)}">`;b.onclick=()=>toggleTable(i);UI.eTableCards.appendChild(b);});}
  function renderHand(){UI.eHand.innerHTML="";if(!state.revealed||current().isAI)return;current().hand.forEach((c,i)=>{const b=document.createElement("button");b.className=`sg-card ${state.selectedHand===i?"selected":""}`;b.style.setProperty("--card-index",i);b.innerHTML=`<img src="${img(c)}" alt="${cardName(c)}">`;b.onclick=()=>selectHand(i);UI.eHand.appendChild(b);});}
  function renderCombos(){UI.eCombos.innerHTML="";const privateTurn=!state.revealed||current().isAI;if(privateTurn){UI.eMessage.textContent=current().isAI?"La IA está calculando la mejor captura.":"Turno oculto.";UI.eLeave.disabled=UI.eCapture.disabled=true;return;}if(state.selectedHand<0){UI.eMessage.textContent="Selecciona una carta de tu mano.";UI.eAdviceTitle.textContent="Suma quince";UI.eAdvice.textContent="Elige una carta; las capturas posibles aparecerán debajo de la mesa.";UI.eLeave.disabled=UI.eCapture.disabled=true;return;}const card=current().hand[state.selectedHand],combos=combosFor(card);combos.forEach((ids,k)=>{const b=document.createElement("button");b.className=`sg-combo ${k===0?"best":""}`;b.textContent=`${cardName(card)} + ${ids.map(i=>cardName(state.table[i])).join(" + ")} = 15`;b.onclick=()=>{state.selectedTable=[...ids];render();};UI.eCombos.appendChild(b);});UI.eLeave.disabled=combos.length>0;UI.eCapture.disabled=!validSelection();UI.eMessage.textContent=combos.length?`${combos.length} captura${combos.length===1?"":"s"} posible${combos.length===1?"":"s"}. Elige una combinación.`:"No hay suma de quince: deja la carta en la mesa.";UI.eAdviceTitle.textContent=combos.length?"Captura disponible":"Sin captura";UI.eAdvice.textContent=combos.length?"Prioriza una escoba, el siete de oros y las capturas con varias cartas.":"Una carta segura evita regalar oros o sietes al siguiente jugador.";}
  function showHandoff(){if(state.mode!=="local"||!state.active)return;state.revealed=false;UI.eHandoffName.textContent=current().name;UI.eHandoff.classList.remove("hidden");render();}
  function revealTurn(){state.revealed=true;UI.eHandoff.classList.add("hidden");render();save();}
  function save(){if(!state.active)return;try{localStorage.setItem(SAVE,JSON.stringify(state));}catch(_){}}
  function continueGame(){try{const s=JSON.parse(localStorage.getItem(SAVE)||"null");if(!s?.active)return;Object.assign(state,s,{revealed:s.mode!=="local"});showGame();if(state.deck.length===0&&state.players.every(p=>p.hand.length===0)){if(state.winner!==null)finishMatch(state.winner);else startHand();return;}render();if(state.mode==="local")showHandoff();else maybeAI();}catch(_){localStorage.removeItem(SAVE);refreshContinue();}}
  function refreshContinue(){try{const s=JSON.parse(localStorage.getItem(SAVE)||"null"),ok=Boolean(s?.active);UI.eContinue.disabled=!ok;UI.eContinueTitle.textContent=ok?`Mano ${s.handNo} · turno de ${s.players[s.current].name}`:"Sin partida pendiente";UI.eContinueMeta.textContent=ok?`${s.players.length} jugadores · objetivo ${s.target}.`:"La mano se guarda después de cada jugada.";}catch(_){UI.eContinue.disabled=true;}}
  function exitMenu(){save();UI.eGame.classList.add("hidden");UI.eWelcome.classList.remove("hidden");refreshContinue();}
  async function toggleMusic(){const a=document.getElementById("backgroundMusic");if(!a)return;if(a.paused){try{await a.play();localStorage.setItem("tuteIaMusicEnabled","true");UI.eMusic.textContent="♫";}catch(_){}}else{a.pause();localStorage.setItem("tuteIaMusicEnabled","false");UI.eMusic.textContent="♩";}window.TuteMusicContinuity?.savePosition();}
  function playCardSound(capture=false){try{const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain(),n=ctx.currentTime;o.type="triangle";o.frequency.setValueAtTime(capture?300:170,n);o.frequency.exponentialRampToValueAtTime(85,n+.08);g.gain.setValueAtTime(capture?.05:.035,n);g.gain.exponentialRampToValueAtTime(.0001,n+.1);o.connect(g).connect(ctx.destination);o.start(n);o.stop(n+.11);setTimeout(()=>ctx.close(),250);}catch(_){}}
  function toast(text){clearTimeout(toastTimer);UI.eToast.textContent=text;UI.eToast.classList.add("visible");toastTimer=setTimeout(()=>UI.eToast.classList.remove("visible"),1800);}
  function log(x){state.log.push(x);if(state.log.length>60)state.log.shift();}
  function initials(n){return n.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();}
  function wait(ms){return new Promise(r=>setTimeout(r,ms));}
  function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
  window.SalaCeroEscobaDebug={deck,value,combosFor,initialEscobas,RANKS:[...RANKS],SUITS:[...SUITS]};
})();
