(()=>{'use strict';const {q,shuffle,show,hide,passScreen,makePlayers,toast,beep,haptic}=SC23;const root=q('#gameRoot');let st={players:[],current:0,dice:[],bid:null,lastBidder:null,round:0};
function setup(){root.innerHTML=`<section class="v23-grid"><div class="v23-panel"><h2>Preparar mesa</h2><p>Cada persona empieza con cinco dados ocultos. El móvil se pasa en cada turno.</p><div class="v23-field"><label>Jugadores</label><select id="n">${[2,3,4,5,6,7,8].map(n=>`<option ${n===4?'selected':''}>${n}</option>`).join('')}</select></div><div class="v23-actions"><button id="start" class="v23-btn primary big wide">Tirar los dados</button></div></div><div class="v23-panel soft"><h3>Orden de las apuestas</h3><p>Para superar una apuesta debes aumentar la cantidad o, manteniendo la cantidad, aumentar la cara del dado.</p></div></section>`;q('#start').onclick=start}
function start(){st.players=makePlayers(+q('#n').value);st.players.forEach(p=>p.dice=5);newRound()}
function roll(n){return Array.from({length:n},()=>1+Math.floor(Math.random()*6))}
function newRound(){st.round++;st.dice=st.players.map(p=>p.dice>0?roll(p.dice):[]);st.bid=null;st.lastBidder=null;const alive=st.players.map((p,i)=>p.dice>0?i:-1).filter(i=>i>=0);if(alive.length===1){gameOver(alive[0]);return}if(st.players[st.current]?.dice<=0)st.current=alive[0];turnPass()}
function aliveNext(from){let i=from;for(let k=0;k<st.players.length;k++){i=(i+1)%st.players.length;if(st.players[i].dice>0)return i}return from}
function scoreboard(){return `<div class="v23-scoreboard">${st.players.map((p,i)=>`<div class="v23-score ${i===st.current?'current':''}"><strong>${p.name}</strong><span>${'🎲'.repeat(p.dice)||'ELIMINADO'}</span></div>`).join('')}</div>`}
function turnPass(){passScreen(`Turno de ${st.players[st.current].name}`,'Los dados de cada jugador son secretos.',turn,'🎲')}
function turn(){const dice=st.dice[st.current];root.innerHTML=`<section class="v23-panel"><div class="v23-status"><span>Ronda <strong>${st.round}</strong></span><span>${st.bid?`Apuesta actual: <strong>${st.bid.count} dados de ${st.bid.face}</strong>`:'Aún no hay apuesta'}</span></div><div style="margin-top:12px">${scoreboard()}</div><h2 class="v23-center" style="margin-top:20px">Tus dados</h2><div class="v23-dice">${dice.map(d=>`<div class="v23-die">${d}</div>`).join('')}</div><div class="v23-grid"><div class="v23-field"><label>Cantidad</label><input id="count" type="number" min="1" max="${st.players.reduce((a,p)=>a+p.dice,0)}" value="${st.bid?st.bid.count:1}"></div><div class="v23-field"><label>Cara</label><select id="face">${[1,2,3,4,5,6].map(f=>`<option ${st.bid&&f===st.bid.face?'selected':''}>${f}</option>`).join('')}</select></div></div><div class="v23-actions"><button id="bid" class="v23-btn primary big">Subir apuesta</button>${st.bid?'<button id="liar" class="v23-btn danger big">¡Mentira!</button>':''}</div></section>`;q('#bid').onclick=makeBid;if(q('#liar'))q('#liar').onclick=challenge}
function makeBid(){const count=+q('#count').value,face=+q('#face').value,total=st.players.reduce((a,p)=>a+p.dice,0);if(count<1||count>total){toast('Cantidad de dados no válida');return}if(st.bid && !(count>st.bid.count || (count===st.bid.count&&face>st.bid.face))){toast('La apuesta debe superar la anterior');return}st.bid={count,face};st.lastBidder=st.current;st.current=aliveNext(st.current);beep(560,.08);turnPass()}
function challenge(){const challenger=st.current,bid=st.bid;const all=st.dice.flat();const hits=all.filter(x=>x===bid.face).length;const liar=hits<bid.count;const loser=liar?st.lastBidder:challenger;st.players[loser].dice--;beep(liar?760:180,.22,liar?'sine':'sawtooth',.07);haptic([70,40,100]);root.innerHTML=`<section class="v23-panel v23-center"><div class="v23-icon" style="margin:0 auto 14px">${liar?'🤥':'😬'}</div><h2>${liar?'¡Era mentira!':'La apuesta era cierta'}</h2><p>Había <strong>${hits}</strong> dado${hits===1?'':'s'} con cara ${bid.face}. ${st.players[loser].name} pierde un dado.</p><div class="v23-dice">${all.map(d=>`<div class="v23-die">${d}</div>`).join('')}</div>${scoreboard()}<div class="v23-actions"><button id="next" class="v23-btn primary big wide">Nueva ronda</button></div></section>`;st.current=loser;if(st.players[loser].dice<=0)st.current=aliveNext(loser);q('#next').onclick=newRound}
function gameOver(i){root.innerHTML=`<section class="v23-panel v23-center"><div class="v23-icon" style="margin:0 auto 14px">🏆</div><h2>${st.players[i].name} gana</h2><p>Ha sido la última persona con dados sobre la mesa.</p><div class="v23-actions"><button id="again" class="v23-btn primary big wide">Jugar otra vez</button></div></section>`;q('#again').onclick=setup}
setup();})();
