(()=>{'use strict';const {q,spanishDeck,cardButton,passScreen,makePlayers,toast,beep,haptic}=SC23;const root=q('#gameRoot');let st={players:[],hands:[],current:0,pile:[],lastPlay:null,selected:new Set(),winner:null};const rankName=r=>({1:'As',2:'Dos',3:'Tres',4:'Cuatro',5:'Cinco',6:'Seis',7:'Siete',10:'Sota',11:'Caballo',12:'Rey'})[r];
function setup(){root.innerHTML=`<section class="v23-panel"><h2>Preparar partida</h2><p>Versión para un solo móvil con la baraja española de Antón.</p><div class="v23-field"><label>Jugadores</label><select id="n">${[2,3,4,5,6].map(n=>`<option ${n===4?'selected':''}>${n}</option>`).join('')}</select></div><div class="v23-actions"><button id="start" class="v23-btn primary big wide">Repartir cartas</button></div></section>`;q('#start').onclick=start}
function start(){st.players=makePlayers(+q('#n').value);const d=spanishDeck();st.hands=st.players.map(()=>[]);d.forEach((c,i)=>st.hands[i%st.players.length].push(c));st.current=0;st.pile=[];st.lastPlay=null;turnPass()}
function nextAlive(from){let i=from;for(let k=0;k<st.players.length;k++){i=(i+1)%st.players.length;if(st.hands[i].length>0)return i}return from}
function score(){return `<div class="v23-scoreboard">${st.players.map((p,i)=>`<div class="v23-score ${i===st.current?'current':''}"><strong>${p.name}</strong><span>${st.hands[i].length} cartas</span></div>`).join('')}</div>`}
function turnPass(){if(st.hands.filter(h=>h.length>0).length<=1){const w=st.hands.findIndex(h=>h.length===0);if(w>=0){gameOver(w);return}}passScreen(`Turno de ${st.players[st.current].name}`,'Solo esta persona debe ver sus cartas.',turn,'🂠')}
function turn(){st.selected=new Set();const canChallenge=!!st.lastPlay;root.innerHTML=`<section class="v23-panel"><div class="v23-status"><span>${st.players[st.current].name}</span><span>Montón: <strong>${st.pile.length}</strong> cartas</span></div>${score()}${canChallenge?`<div class="v23-panel soft"><p style="margin:0"><strong>${st.players[st.lastPlay.player].name}</strong> afirma haber jugado <strong>${st.lastPlay.cards.length} ${rankName(st.lastPlay.claim)}</strong>.</p></div>`:''}<h2 class="v23-center">Tu mano</h2><div id="hand" class="v23-card-row">${st.hands[st.current].map(cardButton).join('')}</div><div class="v23-grid"><div class="v23-field"><label>Declarar valor</label><select id="claim">${[1,2,3,4,5,6,7,10,11,12].map(r=>`<option value="${r}">${rankName(r)}</option>`).join('')}</select></div><div class="v23-panel soft" style="margin:0"><strong id="selCount">0 cartas seleccionadas</strong><p style="margin:4px 0 0">Puedes tirar hasta 4 cartas a la vez.</p></div></div><div class="v23-actions"><button id="play" class="v23-btn primary big" disabled>Jugar boca abajo</button>${canChallenge?'<button id="challenge" class="v23-btn danger big">¡MENTIRA!</button>':''}</div></section>`;root.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>toggle(b));q('#play').onclick=play;if(q('#challenge'))q('#challenge').onclick=challenge}
function toggle(b){const id=b.dataset.card;if(st.selected.has(id)){st.selected.delete(id);b.classList.remove('selected')}else{if(st.selected.size>=4){toast('Máximo 4 cartas');return}st.selected.add(id);b.classList.add('selected')}q('#selCount').textContent=`${st.selected.size} carta${st.selected.size===1?'':'s'} seleccionada${st.selected.size===1?'':'s'}`;q('#play').disabled=st.selected.size===0}
function play(){if(st.lastPlay&&st.hands[st.lastPlay.player].length===0){gameOver(st.lastPlay.player);return}const hand=st.hands[st.current],cards=hand.filter(c=>st.selected.has(c.id));if(!cards.length)return;st.hands[st.current]=hand.filter(c=>!st.selected.has(c.id));st.pile.push(...cards);st.lastPlay={player:st.current,cards,claim:+q('#claim').value};const justEmptied=st.hands[st.current].length===0;st.current=nextAlive(st.current);beep(620,.08);if(justEmptied){/* debe sobrevivir a un posible desafío */}turnPass()}
function challenge(){const challenger=st.current,lp=st.lastPlay;const truth=lp.cards.every(c=>c.rank===lp.claim);const loser=truth?challenger:lp.player;st.hands[loser].push(...st.pile);st.pile=[];st.lastPlay=null;beep(truth?180:760,.25,truth?'sawtooth':'sine',.07);haptic([80,40,100]);root.innerHTML=`<section class="v23-panel v23-center"><div class="v23-icon" style="margin:0 auto 14px">${truth?'😬':'🤥'}</div><h2>${truth?'¡Decía la verdad!':'¡Mentira descubierta!'}</h2><p>${truth?`${st.players[challenger].name} recoge el montón.`:`${st.players[lp.player].name} recoge el montón.`}</p><div class="v23-card-row">${lp.cards.map(cardButton).join('')}</div>${score()}<div class="v23-actions"><button id="next" class="v23-btn primary big wide">Continuar</button></div></section>`;st.current=loser;q('#next').onclick=()=>{const zero=st.hands.findIndex(h=>h.length===0);if(zero>=0)gameOver(zero);else turnPass()}}
function gameOver(i){root.innerHTML=`<section class="v23-panel v23-center"><div class="v23-icon" style="margin:0 auto 14px">🏆</div><h2>${st.players[i].name} se queda sin cartas</h2><p>Partida terminada.</p><div class="v23-actions"><button id="again" class="v23-btn primary big wide">Nueva partida</button></div></section>`;q('#again').onclick=setup}
setup();})();
