(()=>{'use strict';const {q,shuffle,passScreen,beep,haptic}=SC23;const root=q('#gameRoot');const WORDS=['tormenta','pirámide','astronauta','champán','murciélago','volcán','brújula','diamante','cactus','fantasma','semáforo','saxofón','castillo','espejo','tiburón','corona','helado','tren','isla','robot','nube','pirata','motor','guitarra','dragón','hospital','café','maratón','maleta','museo','satélite','desierto','reloj','barbacoa','elefante','cocodrilo','avión','farmacia','casino','película','karaoke','montaña','micrófono','universidad','fotografía','supermercado','discoteca','dentista','paraguas','chimenea','ballena','ascensor','tatuaje','hamburguesa','ordenador','bicicleta','planeta','sirena','detective','naranja','glaciar','laberinto','trompeta','ninja','zombi','tornado','queso','lámpara','telescopio','cometa','anillo','búnker','caballo','submarino','catedral','piano','meteorito','canguro','carnaval','biblioteca'];let st={deck:[],idx:0,team:0,scores:[0,0],round:1,attempts:0,max:6,word:''};
function setup(){st.deck=shuffle(WORDS);st.idx=0;st.team=0;st.scores=[0,0];st.round=1;newWord()}
function teams(){return `<div class="v23-grid"><div class="v23-team ${st.team===0?'active':''}"><strong>Equipo A</strong><span class="points">${st.scores[0]}</span></div><div class="v23-team ${st.team===1?'active':''}"><strong>Equipo B</strong><span class="points">${st.scores[1]}</span></div></div>`}
function newWord(){st.word=st.deck[st.idx++%st.deck.length];st.attempts=0;passScreen(`Portavoz del Equipo ${st.team?'B':'A'}`,'Mira la palabra y luego oculta la pantalla antes de dar tu pista.',showSecret,'🔐')}
function showSecret(){root.innerHTML=`<section class="v23-panel v23-center">${teams()}<span class="v23-kicker">PALABRA SECRETA</span><h2 class="v23-question">${st.word.toUpperCase()}</h2><p>Memorízala. Solo puedes dar una pista de <strong>una palabra</strong>.</p><div class="v23-actions"><button id="hide" class="v23-btn primary big wide">Ocultar y dar pista</button></div></section>`;q('#hide').onclick=guessPhase}
function guessPhase(){st.attempts++;root.innerHTML=`<section class="v23-panel v23-center">${teams()}<div class="v23-status"><span>Intento <strong>${st.attempts}/${st.max}</strong></span><span>Equipo con la pista: <strong>${st.team?'B':'A'}</strong></span></div><div class="v23-icon" style="margin:20px auto">🔐</div><h2>Una pista. Una palabra.</h2><p>El portavoz da ahora su pista en voz alta. El equipo hace un único intento.</p><div class="v23-actions"><button id="yes" class="v23-btn good big">¡Acertado!</button><button id="no" class="v23-btn danger big">No acertado</button></div></section>`;q('#yes').onclick=win;q('#no').onclick=miss}
function win(){const pts=Math.max(1,7-st.attempts);st.scores[st.team]+=pts;beep(880,.16);haptic(80);root.innerHTML=`<section class="v23-panel v23-center">${teams()}<div class="v23-icon" style="margin:18px auto">🏆</div><h2>¡${st.word.toUpperCase()}!</h2><p>Equipo ${st.team?'B':'A'} suma <strong>${pts}</strong> punto${pts===1?'':'s'}.</p><div class="v23-actions"><button id="next" class="v23-btn primary big wide">Nueva palabra</button></div></section>`;q('#next').onclick=()=>{st.team=1-st.team;st.round++;newWord()}}
function miss(){beep(220,.1,'square',.04);if(st.attempts>=st.max){root.innerHTML=`<section class="v23-panel v23-center">${teams()}<h2>Nadie la consiguió</h2><p>La palabra era <strong>${st.word.toUpperCase()}</strong>.</p><div class="v23-actions"><button id="next" class="v23-btn primary big wide">Siguiente palabra</button></div></section>`;q('#next').onclick=()=>{st.team=1-st.team;newWord()};return}st.team=1-st.team;passScreen(`Portavoz del Equipo ${st.team?'B':'A'}`,'La palabra sigue siendo la misma. Mira en secreto y da una nueva pista.',showSecret,'🔐')}
setup();})();
