(()=>{'use strict';const {q,spanishDeck,cardButton,passScreen,makePlayers,pick,beep,haptic}=SC23;const root=q('#gameRoot');let st={players:[],hands:[],deck:[],pyramid:[],reveal:0,scores:[],memoryIdx:0,busPlayer:0,busStep:0,busCards:[]};const red=s=>s==='oros'||s==='copas';
function setup(){root.innerHTML=`<section class="v23-panel"><h2>Preparar La Pirámide</h2><p>Cada jugador memoriza cuatro cartas en privado. Después se revela la pirámide fila a fila.</p><div class="v23-field"><label>Jugadores</label><select id="n">${Array.from({length:5},(_,i)=>i+2).map(n=>`<option ${n===5?'selected':''}>${n}</option>`).join('')}</select></div><div class="v23-actions"><button id="start" class="v23-btn primary big wide">Repartir y memorizar</button></div></section>`;q('#start').onclick=start}
function start(){st.players=makePlayers(+q('#n').value);st.deck=spanishDeck();st.hands=st.players.map(()=>Array.from({length:4},()=>st.deck.pop()));st.pyramid=Array.from({length:15},()=>st.deck.pop());st.reveal=0;st.scores=st.players.map(()=>0);st.memoryIdx=0;memoryPass()}
function memoryPass(){if(st.memoryIdx>=st.players.length){pyramid();return}const i=st.memoryIdx;passScreen(`Memoriza: ${st.players[i].name}`,'Tienes unos segundos para recordar tus cuatro cartas.',()=>showHand(i),'🧠')}
function showHand(i){root.innerHTML=`<section class="v23-panel v23-center"><div class="v23-status"><span>${st.players[i].name}</span><span>Memoriza valor y palo</span></div><h2>Estas son tus cuatro cartas</h2><div class="v23-card-row">${st.hands[i].map(cardButton).join('')}</div><p>Cuando las tengas, oculta la pantalla y pasa el móvil.</p><div class="v23-actions"><button id="done" class="v23-btn primary big wide">Ya las tengo</button></div></section>`;q('#done').onclick=()=>{st.memoryIdx++;memoryPass()}}
function rowOf(index){if(index<5)return 1;if(index<9)return 2;if(index<12)return 3;if(index<14)return 4;return 5}function score(){return `<div class="v23-scoreboard">${st.players.map((p,i)=>`<div class="v23-score"><strong>${p.name}</strong><span>${st.scores[i]} pts</span></div>`).join('')}</div>`}
function pyramid(){const last=st.reveal?st.pyramid[st.reveal-1]:null;root.innerHTML=`<section class="v23-panel"><div class="v23-status"><span>Pirámide</span><span>${st.reveal}/15 reveladas</span></div><h2 class="v23-center">${last?`Última carta: ${last.rank} de ${last.suit}`:'Todo listo'}</h2><div class="v23-pyramid">${renderPyramid()}</div>${last?`<p class="v23-subtitle">Fila ${rowOf(st.reveal-1)}: cada jugador que recuerde tener un <strong>${last.rank}</strong> suma ${rowOf(st.reveal-1)} punto${rowOf(st.reveal-1)===1?'':'s'} por coincidencia.</p><div class="v23-chipset">${st.players.map((p,i)=>`<button class="v23-chip" data-award="${i}">+${rowOf(st.reveal-1)} ${p.name}</button>`).join('')}</div>`:''}<div style="margin-top:14px">${score()}</div><div class="v23-actions"><button id="next" class="v23-btn primary big wide">${st.reveal<15?'Revelar siguiente carta':'Ir al Autobús'}</button></div></section>`;root.querySelectorAll('[data-award]').forEach(b=>b.onclick=()=>{const i=+b.dataset.award,pts=rowOf(st.reveal-1);st.scores[i]+=pts;b.disabled=true;b.textContent='SUMADO';scoreRefresh()});q('#next').onclick=()=>{if(st.reveal<15){st.reveal++;beep(620,.07);pyramid()}else{startBus()}}}
function renderPyramid(){let html='',idx=0;for(let row=1;row<=5;row++){const blanks=5-row;for(let b=0;b<blanks;b++)html+='<div class="empty"></div>';for(let c=0;c<row;c++,idx++){const card=st.pyramid[idx];html+=idx<st.reveal?cardButton(card,'tiny'):`<div class="v23-playing-card back tiny"></div>`}}return html}function scoreRefresh(){const box=root.querySelector('.v23-scoreboard');if(box)box.outerHTML=score()}
function startBus(){const min=Math.min(...st.scores);st.busPlayer=st.scores.indexOf(min);st.busStep=0;st.busCards=[st.deck.pop()];bus()}
const BUS=[['Color',c=>red(c.suit)?'rojo':'negro',['rojo','negro']],['Mayor o menor',null,['mayor','menor']],['Dentro o fuera',null,['dentro','fuera']],['¿Qué palo?',c=>c.suit,['oros','copas','espadas','bastos']]];
function bus(){if(st.busStep>=4){root.innerHTML=`<section class="v23-panel v23-center"><div class="v23-icon" style="margin:0 auto 15px">🚌</div><h2>${st.players[st.busPlayer].name} baja del Autobús</h2><p>Ha superado las cuatro predicciones seguidas.</p><div class="v23-actions"><button id="again" class="v23-btn primary big wide">Nueva partida</button></div></section>`;q('#again').onclick=setup;return}const [label,,opts]=BUS[st.busStep];root.innerHTML=`<section class="v23-panel v23-center"><div class="v23-status"><span>Autobús · ${st.players[st.busPlayer].name}</span><span>Paso ${st.busStep+1}/4</span></div><h2>${label}</h2><div class="v23-card-row">${st.busCards.map(cardButton).join('')}<div class="v23-playing-card back"></div></div><div class="v23-chipset">${opts.map(o=>`<button class="v23-chip" data-guess="${o}">${o.toUpperCase()}</button>`).join('')}</div></section>`;root.querySelectorAll('[data-guess]').forEach(b=>b.onclick=()=>guess(b.dataset.guess))}
function guess(g){const prev=st.busCards.at(-1),next=st.deck.pop()||spanishDeck()[0];let ok=false;if(st.busStep===0)ok=g===(red(next.suit)?'rojo':'negro');else if(st.busStep===1)ok=g===(next.rank>prev.rank?'mayor':'menor');else if(st.busStep===2){const vals=st.busCards.map(c=>c.rank),lo=Math.min(...vals),hi=Math.max(...vals);ok=g===((next.rank>lo&&next.rank<hi)?'dentro':'fuera')}else ok=g===next.suit;st.busCards.push(next);if(ok){st.busStep++;beep(780,.09);bus()}else{beep(160,.3,'sawtooth',.07);haptic([80,40,120]);st.busStep=0;st.busCards=[st.deck.pop()||spanishDeck()[0]];SC23.toast('Fallaste: el Autobús vuelve al principio');setTimeout(bus,500)}}
setup();})();
