(()=>{'use strict';const {q,spanishDeck,cardButton,passScreen,makePlayers,toast,beep}=SC23;const root=q('#gameRoot');let st={players:[],hands:[],current:0,lead:null,passes:0,selected:new Set(),finished:[]};const power=r=>r===2?13:r;const name=r=>({1:'As',2:'Dos',3:'Tres',4:'Cuatro',5:'Cinco',6:'Seis',7:'Siete',10:'Sota',11:'Caballo',12:'Rey'})[r];
function setup(){root.innerHTML=`<section class="v23-grid"><div class="v23-panel"><h2>Presidente Express</h2><p>Una versión rápida, limpia y totalmente local. El 2 es la carta más alta.</p><div class="v23-field"><label>Jugadores</label><select id="n">${[3,4,5,6].map(n=>`<option ${n===4?'selected':''}>${n}</option>`).join('')}</select></div><div class="v23-actions"><button id="start" class="v23-btn primary big wide">Repartir</button></div></div><div class="v23-panel soft"><h3>Objetivo</h3><p>Vacía tu mano antes que los demás. Puedes jugar varias cartas iguales, pero debes respetar la cantidad de cartas de la jugada anterior.</p></div></section>`;q('#start').onclick=start}
function start(){st.players=makePlayers(+q('#n').value);const d=spanishDeck();st.hands=st.players.map(()=>[]);d.forEach((c,i)=>st.hands[i%st.players.length].push(c));st.hands.forEach(h=>h.sort((a,b)=>power(a.rank)-power(b.rank)));st.current=0;st.lead=null;st.passes=0;st.finished=[];turnPass()}
function activeIndices(){return st.players.map((_,i)=>!st.finished.includes(i)?i:-1).filter(i=>i>=0)}function next(from){let i=from;for(let k=0;k<st.players.length;k++){i=(i+1)%st.players.length;if(!st.finished.includes(i))return i}return from}
function score(){return `<div class="v23-scoreboard">${st.players.map((p,i)=>`<div class="v23-score ${i===st.current?'current':''}"><strong>${p.name}</strong><span>${st.finished.includes(i)?`Puesto ${st.finished.indexOf(i)+1}`:`${st.hands[i].length} cartas`}</span></div>`).join('')}</div>`}
function turnPass(){if(st.finished.length>=st.players.length-1){const last=st.players.map((_,i)=>i).find(i=>!st.finished.includes(i));st.finished.push(last);results();return}passScreen(`Turno de ${st.players[st.current].name}`,'Solo esta persona debe ver la mano.',turn,'👑')}
function turn(){st.selected=new Set();root.innerHTML=`<section class="v23-panel"><div class="v23-status"><span>${st.players[st.current].name}</span><span>${st.lead?`Hay que superar <strong>${st.lead.count} × ${name(st.lead.rank)}</strong>`:'Tú abres la baza'}</span></div>${score()}<h2 class="v23-center">Tu mano</h2><div id="hand" class="v23-card-row">${st.hands[st.current].map(cardButton).join('')}</div><div class="v23-actions"><button id="play" class="v23-btn primary big" disabled>Jugar selección</button>${st.lead?'<button id="pass" class="v23-btn big">Pasar</button>':''}</div></section>`;root.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>toggle(b));q('#play').onclick=play;if(q('#pass'))q('#pass').onclick=pass}
function toggle(b){const id=b.dataset.card,card=st.hands[st.current].find(c=>c.id===id);if(st.selected.has(id)){st.selected.delete(id);b.classList.remove('selected')}else{const selCards=st.hands[st.current].filter(c=>st.selected.has(c.id));if(selCards.length&&selCards[0].rank!==card.rank){toast('Todas las cartas deben tener el mismo valor');return}st.selected.add(id);b.classList.add('selected')}q('#play').disabled=st.selected.size===0}
function play(){const h=st.hands[st.current],cards=h.filter(c=>st.selected.has(c.id)),rank=cards[0]?.rank;if(!cards.length)return;if(st.lead){if(cards.length!==st.lead.count){toast(`Debes jugar ${st.lead.count} carta${st.lead.count===1?'':'s'}`);return}if(power(rank)<=power(st.lead.rank)){toast('Debes superar el valor anterior');return}}st.hands[st.current]=h.filter(c=>!st.selected.has(c.id));st.lead={rank,count:cards.length,last:st.current};st.passes=0;beep(650,.08);if(st.hands[st.current].length===0){st.finished.push(st.current)}st.current=next(st.current);turnPass()}
function pass(){st.passes++;const active=activeIndices().length;if(st.passes>=active-1){const opener=st.lead.last;st.lead=null;st.passes=0;st.current=st.finished.includes(opener)?next(opener):opener;beep(420,.08);turnPass();return}st.current=next(st.current);turnPass()}
function results(){root.innerHTML=`<section class="v23-panel v23-center"><div class="v23-icon" style="margin:0 auto 16px">👑</div><h2>Clasificación</h2><div class="v23-answer-list">${st.finished.map((i,pos)=>`<div class="v23-answer"><span class="badge">${pos+1}</span><p><strong>${st.players[i].name}</strong></p><strong>${pos===0?'PRESIDENTE':pos===1?'VICEPRESIDENTE':pos===st.finished.length-1?'ÚLTIMO':'PUEBLO'}</strong></div>`).join('')}</div><div class="v23-actions"><button id="again" class="v23-btn primary big wide">Jugar otra</button></div></section>`;q('#again').onclick=setup}
setup();})();
