(()=>{'use strict';const {q,pick,beep,haptic}=SC23;const root=q('#gameRoot');const TYPES=['Categoría','Duelo','Mímica','Pregunta','Bomba','Todos contra uno','Imitación','Memoria','Reto exprés','Confesión','Adivina','Caos total'];const BANK={
'Categoría':['Decid nombres de ciudades sin repetir hasta que alguien falle.','Ronda rápida: marcas de ropa. Quien tarde más de 3 segundos pierde.','Animales que empiecen por consonante. Sin repetir.','Películas conocidas: una por persona hasta que alguien se bloquee.'],
'Duelo':['Dos personas: piedra, papel o tijera al mejor de 3.','Duelo de miradas. La primera persona que se ría pierde.','Decid alternativamente países. Tres segundos por respuesta.','Duelo de equilibrio: a la pata coja. Último en aguantar gana.'],
'Mímica':['Imita a un camarero saturado sin hablar.','Representa una película famosa sin sonidos.','Haz de astronauta descubriendo algo horrible.','Imita a alguien intentando aparcar en un hueco imposible.'],
'Pregunta':['¿Qué compra absurda defenderías aunque nadie la entienda?','¿Qué habilidad inútil te gustaría dominar?','¿Qué sería lo peor de vivir todos juntos?','¿Qué famoso sería el peor compañero de piso?'],
'Bomba':['Pasad el móvil diciendo comidas. Quien dude, pierde.','Pasad el móvil diciendo nombres propios. Dos segundos por turno.','Decid cosas que hay en un aeropuerto. Sin repetir.','Decid palabras que empiecen por C hasta que alguien falle.'],
'Todos contra uno':['Elegid a una persona. Tiene 20 segundos para hacer reír al resto.','Una persona piensa un objeto. El grupo tiene 10 preguntas de sí/no.','Una persona debe aguantar 20 segundos sin decir sí ni no.','El grupo elige una canción y una persona debe reconocerla tarareada.'],
'Imitación':['Imita a otra persona del grupo hasta que la adivinen.','Haz una imitación de un entrenador enfadado.','Imita a un presentador de teletienda vendiendo un objeto cercano.','Imita a alguien despertándose cinco minutos tarde para un vuelo.'],
'Memoria':['Mirad la habitación 10 segundos. Cerrad los ojos y decid objetos por turnos.','Primera persona dice una palabra. Cada una repite la cadena y añade otra.','Memorizad seis palabras: perro, cobre, playa, siete, nube, motor. Repetidlas al revés.','Una persona cambia algo pequeño de su aspecto. El resto debe detectarlo.'],
'Reto exprés':['Tienes 15 segundos para encontrar algo azul.','Construye la torre más alta posible con tres objetos cercanos.','Di el abecedario desde la Z todo lo rápido que puedas.','Haz 10 sentadillas mientras dices nombres de países.'],
'Confesión':['Cuenta una manía que casi nadie conozca.','¿Cuál ha sido tu excusa más ridícula para cancelar un plan?','¿Qué cosa haces mucho peor de lo que la gente cree?','Confiesa una comida popular que no soportes.'],
'Adivina':['Piensa un animal. El resto tiene 5 preguntas de sí/no.','Piensa una película. Solo puedes responder sí/no.','Piensa una persona famosa. El grupo tiene 8 preguntas.','Piensa un objeto de esta habitación. Cinco preguntas máximo.'],
'Caos total':['Todo el mundo cambia de sitio. Último en sentarse pierde.','Durante 30 segundos nadie puede decir la letra A.','Elegid una palabra prohibida para los próximos 3 giros.','La siguiente persona debe completar dos retos seguidos.']};let rot=0,busy=false;
function render(){root.innerHTML=`<section class="v23-panel v23-center"><div class="v23-wheel-wrap"><div class="v23-wheel-pointer"></div><div id="wheel" class="v23-wheel"></div></div><h2 id="title">Gira y acepta lo que salga</h2><p id="challenge">Doce tipos de prueba. Cero preparación.</p><div class="v23-actions"><button id="spin" class="v23-btn primary big wide">GIRAR LA RULETA</button></div></section>`;q('#spin').onclick=spin}
function spin(){if(busy)return;busy=true;const idx=Math.floor(Math.random()*TYPES.length);const extra=1440+idx*30+Math.floor(Math.random()*360);rot+=extra;q('#wheel').style.transform=`rotate(${rot}deg)`;q('#spin').disabled=true;beep(380,.06);setTimeout(()=>{const type=TYPES[idx];q('#title').textContent=type;q('#challenge').textContent=pick(BANK[type]);q('#spin').disabled=false;q('#spin').textContent='VOLVER A GIRAR';busy=false;beep(860,.14);haptic(70)},4300)}render();})();
