(()=>{'use strict';const {q,spanishDeck,cardButton,passScreen,makePlayers,toast,beep,haptic}=SC23;const root=q('#gameRoot');let st={players:[],deck:[],turn:0,bank:[],phase:'bet',bets:[],hands:[],stood:[]};
const val=c=>c.rank>=10?.5:c.rank;const total=h=>Math.round(h.reduce((a,c)=>a+val(c),0)*2)/2;const fmt=n=>Number.isInteger(n)?String(n):String(n).replace('.',',');
function setup(){root.innerHTML=`<section class="v23-grid"><div class="v23-panel"><h2>Mesa de 7 y Media</h2><p>La banca es Antón. Cada jugador empieza con 100 fichas virtuales.</p><div class="v23-field"><label>Jugadores</label><select id="n">${[1,2,3,4,5,6].map(n=>`<option ${n===2?'selected':''}>${n}</option>`).join('')}</select></div><div class="v23-actions"><button id="start" class="v23-btn primary big wide">Abrir la mesa</button></div></div><div class="v23-panel soft"><h3>Valores</h3><p>As–7 valen su número. Sota, caballo y rey valen medio punto. Pasarse de 7½ significa perder la apuesta.</p></div></section>`;q('#start').onclick=start}
function start(){st.players=makePlayers(+q('#n').value);st.players.forEach(p=>p.chips=100);newHand()}
function newHand(){st.deck=spanishDeck();st.turn=0;st.bank=[];st.bets=Array(st.players.length).fill(0);st.hands=st.players.map(()=>[]);st.stood=Array(st.players.length).fill(false);takeBets()}
function scores(){return `<div class="v23-scoreboard">${st.players.map((p,i)=>`<div class="v23-score ${i===st.turn?'current':''}"><strong>${p.name}</strong><span>${p.chips} fichas</span></div>`).join('')}</div>`}
function takeBets(){if(st.turn>=st.players.length){deal();return}if(st.players[st.turn].chips<=0){st.turn++;takeBets();return}passScreen(`Apuesta de ${st.players[st.turn].name}`,'Elige tu apuesta sin que el resto toque la pantalla.',()=>renderBet(),'7½')}
function renderBet(){const p=st.players[st.turn];const opts=[5,10,20,50].filter(x=>x<=p.chips);root.innerHTML=`<section class="v23-panel"><div class="v23-status"><span>Jugador: <strong>${p.name}</strong></span><span>Saldo: <strong>${p.chips}</strong></span></div><h2 class="v23-center" style="margin-top:22px">¿Cuánto apuestas?</h2><div class="v23-chipset">${opts.map(x=>`<button class="v23-chip" data-bet="${x}">${x} fichas</button>`).join('')}<button class="v23-chip" data-bet="${p.chips}">Todo (${p.chips})</button></div></section>`;root.querySelectorAll('[data-bet]').forEach(b=>b.onclick=()=>{st.bets[st.turn]=+b.dataset.bet;st.players[st.turn].chips-=+b.dataset.bet;st.turn++;takeBets()})}
function deal(){st.turn=0;st.hands.forEach((h,i)=>{if(st.bets[i]>0)h.push(st.deck.pop())});st.bank=[st.deck.pop()];nextPlayer()}
function nextPlayer(){while(st.turn<st.players.length&&(st.bets[st.turn]===0||st.stood[st.turn]))st.turn++;if(st.turn>=st.players.length){dealer();return}passScreen(`Turno de ${st.players[st.turn].name}`,'Solo esta persona debe ver su mano.',renderTurn,'🃏')}
function renderTurn(){const i=st.turn,h=st.hands[i],t=total(h),bust=t>7.5;root.innerHTML=`<section class="v23-panel"><div class="v23-status"><span>${st.players[i].name}</span><span>Apuesta <strong>${st.bets[i]}</strong></span></div><h2 class="v23-center">Tu mano · ${fmt(t)}</h2><div class="v23-card-row">${h.map(c=>cardButton(c)).join('')}</div>${scores()}<div class="v23-actions"><button id="hit" class="v23-btn primary big" ${bust?'disabled':''}>Pedir carta</button><button id="stand" class="v23-btn big" ${bust?'disabled':''}>Plantarse</button></div></section>`;if(bust){beep(160,.25,'sawtooth',.07);haptic([60,40,100]);st.stood[i]=true;setTimeout(()=>{st.turn++;nextPlayer()},700);return}q('#hit').onclick=()=>{h.push(st.deck.pop());beep(660,.06);renderTurn()};q('#stand').onclick=()=>{st.stood[i]=true;st.turn++;nextPlayer()}}
function dealer(){while(total(st.bank)<5.5)st.bank.push(st.deck.pop());const bt=total(st.bank);st.players.forEach((p,i)=>{if(st.bets[i]<=0)return;const pt=total(st.hands[i]);if(pt<=7.5 && (bt>7.5||pt>bt))p.chips+=st.bets[i]*2});const broke=st.players.every(p=>p.chips<=0);root.innerHTML=`<section class="v23-panel"><div class="v23-status"><span>Banca de Antón</span><span>Total <strong>${fmt(bt)}</strong></span></div><h2 class="v23-center">La banca enseña sus cartas</h2><div class="v23-card-row">${st.bank.map(c=>cardButton(c)).join('')}</div><div class="v23-answer-list">${st.players.map((p,i)=>{const pt=total(st.hands[i]);const won=st.bets[i]>0&&pt<=7.5&&(bt>7.5||pt>bt);return `<div class="v23-answer"><span class="badge">${i+1}</span><p><strong>${p.name}</strong> · ${fmt(pt)} puntos · apuesta ${st.bets[i]}</p><strong>${st.bets[i]===0?'SIN APUESTA':won?'GANA':'PIERDE'}</strong></div>`}).join('')}</div>${scores()}<div class="v23-actions"><button id="next" class="v23-btn primary big wide">${broke?'Reiniciar casino':'Siguiente mano'}</button></div></section>`;q('#next').onclick=()=>broke?setup():newHand()}
setup();})();
